### PR TITLE
[backend] fix(resource): validate user input for resource access (#5573)

### LINKED ISSUE #5573: Agent, implant binaries requests don't validate user input
## Description
User input is not validated on endpoints:
 
* `/api/agent/installer/openaev/{platform}/{installationMode}/{token}`
* `/api/agent/package/openaev/{platform}/{architecture}/{installationMode}`
* `/api/agent/executable/openaev/{platform}/{architecture}`
* `/api/implant/openaev/{platform}/{architecture}`

the `platform`, `architecture` and `installationMode` parts are  user-supplied and used verbatim for resource fetching in the backend.

### PR DESCRIPTION
**Pull request by antoinemzs**
### Proposed changes

* Validate user input on binary fetching endpoints (agents, implants)

### Testing Instructions

1. regression testing only

### Related issues

* Closes #5573

### CODE REVIEW

File: openaev-model/src/main/java/io/openaev/database/model/Endpoint.java [hunk 1]
```diff
@@ -86,11 +86,12 @@ public static List<String> getAllNamesAsStrings() {
      */
     public static PLATFORM_TYPE fromString(String value) {
       if (value == null) return Unknown;
-      try {
-        return PLATFORM_TYPE.valueOf(value);
-      } catch (IllegalArgumentException e) {
-        return Unknown;
+      for (PLATFORM_TYPE type : PLATFORM_TYPE.values()) {
```
Comment (RomuDeuxfois) [inline openaev-model/src/main/java/io/openaev/database/model/Endpoint.java:89]: **nitpick**: Why change this? It may have a small performance impact depending on the enum size.

File: openaev-api/src/main/java/io/openaev/utils/AgentUtils.java [hunk 2]
```diff
@@ -57,6 +89,41 @@ public static String getCanonicalArchitectureString(String architecture) {
...
+    INSTALLATION_MODE(String value) {
+      this.value = value;
+    }
+
+    public String getValue() {
+      return this.value;
+    }
+
+    public static INSTALLATION_MODE fromString(String candidate) {
+      for (INSTALLATION_MODE mode : INSTALLATION_MODE.values()) {
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/utils/AgentUtils.java:108]: **nitpick**: I prefer using valueOf

File: openaev-api/src/main/java/io/openaev/rest/executor/ExecutorApi.java [hunk 3]
```diff
@@ -281,28 +274,20 @@ public Executor registerExecutor(
...
+    String resolvedInstallationMode = AgentUtils.getSupportedInstallationMode(installationMode);
+    String resolvedPlatform =
+        AgentUtils.normaliseSupportedAgentPlatform(platform).name().toLowerCase();
+    String resolvedArch = AgentUtils.normaliseSupportedAgentArch(architecture).name().toLowerCase();
 
     byte[] file = null;
     String filename = null;
 
-    if (platform.equals("windows")) {
+    if (resolvedPlatform.equals("windows")) {
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/rest/executor/ExecutorApi.java:285]: **nitpick**: This code can be extract to a dedicated service relatif to agent or implant (InjectorApi) to separate the logic

**Comment by antoinemzs** [comment]
Addressing all three comments here:

  `valueOf` does not allow for case insensitive search. The logic change is that I'm changing this function to also allow checking against the user-provided values in the download URLs; the enum is quite small so I don't see a real performance impact.

other considered (and discarded) solutions to keep using `valueOf`:

* normalising the searched string to either full capitals or full minuscules; requires changing the enum values to match the chosen casing, and requires a migration everywhere the enum value was persisted
* use a separate dictionary to normalise the input string to match the existing casing in the enum (e.g. capital letter then minuscules and a special-case for "MacOS"; felt a bit fiddly and definitly duplicative.

**Review by RomuDeuxfois — APPROVED** [review]
