### PR TITLE
[backend] fix(logout): fix logout redirect url (#4445)

### LINKED ISSUE #4445: Log out issue from the Simulations > Animation tab
## Description
When trying to log out from the Simulations 'Animations' tab it results in an error
'Something went wrong. Please refresh the page or try again later'

## Environment
1. SaaS 2.0.4

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Click on a simulation and open it
2. Go to the Animation tab
3. Click on icon (top right) and select Logout.

## Expected Output
Normal logout to occur (without error)

## Actual Output
Error as per screenshot below

## Screenshots (optional)

Image

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* When having a different url than the base-url (which can happen if you're in the middle of a renaming and some persons uses the old url and others the new one), you get a CSRF error during logout. This change uses the referer url.
*

### Testing Instructions

1. Login
2. Logout
3. Check there are no errors

### Related issues

* Closes #4445 
*

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comment
Given that the issue is linked to additional host in the deployment, I need this PR to be merged to master so I can test it fully.

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java [hunk 1]
```diff
@@ -92,10 +92,19 @@ public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
...
+                        (request, response, authentication) -> {
+                          if (request.getHeader("Referer").contains("localhost")
+                              || request.getHeader("Referer").contains("127.0.0.1")) {
+                            response.sendRedirect(
+                                env.getProperty("openaev.base-url", String.class, "/")
+                                    + env.getProperty(
+                                        "openaev.logout-success-url", String.class, "/"));
+                          } else {
+                            response.sendRedirect(
+                                env.getProperty("openaev.logout-success-url", String.class, "/"));
```
Comment (guillaumejparis) [inline openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java]: just to be sure we do not need base url here because it is something that only the frontend uses ?

Comment (Dimfacion) [reply openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java]: (Not relevant anymore since last changes, resolving the conversation)
