### PR TITLE
[backend] Fix payload import

### LINKED ISSUE #3171: Introduce remediation for technical inject
## Context

- Display custom remediation at inject, simulation and scenario 
- Be able to define custom remediation in an inject

=> Show only remediation of inject not detected/blocked

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

* Add import payload remediations (inject, simulation, scenario)

### Testing Instructions

1. Create a paylaod with a remediation
2. Cree un scenario, simualion, inject and use the created paylaod in any inject
3. Execute scenario, simulation.. 
4. Export scenario, simulation, inject
5. Import scneario, simualtion, inject
6. Check remediations are presents.

### Related issues

* Closes #3171 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java [hunk 1]
```diff
@@ -1290,6 +1297,37 @@ private String importPayload(@NotNull final JsonNode payloadNode, Map<String, Ba
...
+
+      if (collector.isPresent()) {
+        if (valueNode == null || valueNode.asText().trim().isEmpty()) {
+          detectionRemediationInputs.add(buildDetectionRemediationFromJsonNode(detectionNode));
+        }
+      } else {
+        log.warn("Import Payload: Missing Collector type: {}", type);
+      }
+    }
+    return detectionRemediationInputs;
```
Comment (antoinemzs) [inline openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java]: TODO: perhaps it is feasible to sneak in a test of two to check that this works correctly. There should be ample examples in the test classes from last time we modified the import class.

File: openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java [hunk 2]
```diff
@@ -1290,6 +1297,37 @@ private String importPayload(@NotNull final JsonNode payloadNode, Map<String, Ba
...
+      JsonNode valueNode = detectionNode.get("detection_remediation_values");
+      String type = detectionNode.get("detection_remediation_collector").textValue();
+      Optional<Collector> collector = collectorRepository.findByType(type);
+
+      if (collector.isPresent()) {
+        if (valueNode == null || valueNode.asText().trim().isEmpty()) {
+          detectionRemediationInputs.add(buildDetectionRemediationFromJsonNode(detectionNode));
+        }
+      } else {
+        log.warn("Import Payload: Missing Collector type: {}", type);
```
Comment (antoinemzs) [inline openbas-api/src/main/java/io/openbas/importer/V1_DataImporter.java]: suggestion: Need a better error message stating the importer was creating detection remediation objects, and that this a skip, not fatal (ok for warning level)

**Review by antoinemzs — DISMISSED** [review]
