### PR TITLE
[backend] fix(mail): missing inject id on footers (#4957)

### LINKED ISSUE #4957: No any inject id into mail received by mail sender injects
## Description

When a mail is sent, we should see the inject_id on footer

## Environment

1. OS (where OpenAEV server runs): all
2. OpenAEV version: 2.1.7
3. OpenAEV client: frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a simulation or a scenario with a mail sender inject
2. Run the simulation or scenario
3. Received mail should include a footer with inject_id

## Expected Output

Image

## Actual Output

Image

## Other informations

Full fix will come with 2.2.0 with this [PR](https://github.com/OpenAEV-Platform/openaev/pull/4850)

### PR DESCRIPTION
**Pull request by gabriel-peze**
### Proposed changes

* Fix missing inject id on footers mail

### Testing Instructions

1. Create a simulation or a scenario with a mail sender inject
2. Run the simulation or scenario
3. Received mail should include a footer with inject_id

### Related issues

* Closes #4957

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/injectors/email/model/EmailContent.java [hunk 1]
```diff
@@ -47,7 +47,7 @@ public String buildMessage(ExecutableInject injection, boolean imapEnabled) {
     }
     data.append(START_DIV).append(body).append(END_DIV);
     // If imap is enable we need to inject the id marker
```
Comment (MarineLeM) [inline openaev-api/src/main/java/io/openaev/injectors/email/model/EmailContent.java]: correct the comments or remove it, to be consistent with your modification
