### PR TITLE
[backend] fix: openAEV scenario overview takes a while to display (#4400)

### LINKED ISSUE #4400: OpenAEV scenario take a while to display when created from OpenCTI
## Description

When a scenario is created in OpenCTI and then loaded in OpenAEV, the scenario takes an excessive amount of time to display

Steps to Reproduce:

1 Create a scenario from OpenCTI
2 Open or load the corresponding scenario in OpenAEV
3 Observe the loading time

Expected Result

The scenario should load and display within a reasonable amount of time (a few seconds)

Actual Result

The scenario takes ~30 seconds to display when it contains a large number of injects (e.g., 260 injects)

Impact

Slows down workflow during scenario creation and validation

 Improvement 

Implement a threshold or optimization mechanism to prevent extremely long loading times when scenarios include a high number of injects

Could be reproduced consistently.
Exemple here:
https://testing.obas.staging.filigran.io/admin/scenarios/ad05bb33-fc8e-4a63-b0ae-71dd0e4f441b

The  timing metrics:

Image

Image

### PR DESCRIPTION
**Pull request by damgouj**
### Proposed changes

* Use native query to improve perf to get main information for the overview scenario page

### Testing Instructions

1. Create/generate a scenario with a lot of data (injects, kill chain phases, teams,...)
2. Go to the overview page of this scenario

### Related issues

* Closes #4400 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/dto/KillChainPhaseDTO.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
+package io.openaev.dto;
+
+import com.fasterxml.jackson.annotation.JsonProperty;
+import lombok.Data;
+
+@Data
+public class KillChainPhaseDTO {
```
Comment (damgouj) [inline openaev-api/src/main/java/io/openaev/dto/KillChainPhaseDTO.java]: DTO -> @ Builder + delete dto folder and see Output

Comment (savacano28) [inline openaev-api/src/main/java/io/openaev/dto/KillChainPhaseDTO.java]: Maybe check if we have already these dtos in our code base, ty.

File: openaev-model/src/main/java/io/openaev/database/raw/RawScenarioQuery.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
+package io.openaev.database.raw;
+
+import java.time.Instant;
+import java.util.Set;
+
+public interface RawScenarioQuery {
```
Comment (savacano28) [inline openaev-model/src/main/java/io/openaev/database/raw/RawScenarioQuery.java]: Maybe could you please RawScenario ->RawScenarioSimple and keep this one as RawScenario, thank you :)

**Comment by savacano28** [comment]
Tested OK: 
6.15 s (master) ->129.28 ms (branch)

**Review by savacano28 — APPROVED** [review]
