### PR TITLE
[backend] fix(inject): inject expectations with existing results are overwritten when expiration_time is set (#4532)

### LINKED ISSUE #4532: Inject expectations with existing results are overwritten when expiration_time is set
## Description

When multiple inject expectations exist for the same asset (some already detected / prevented, others undetected / unprevented), valid detected/prevented expectations are incorrectly reverted to undetected/unprevented after 45 minutes (collector delta).

Example:

Inject A is detected/prevented → marked detected/prevented 

Inject B is never detected → stays failed (expected)

But when the expectation reaches expiration:

Inject A, which was already detected/prevented, is overwritten and becomes failed again.

This happens only when at least one inject remains undetected.

Image

Image

## Environment

1. OpenAEV 2.0.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a simulation with 2 injects: one inject is correctly marked as prevented/detected, while the other is not (because Defender never actually caught it — which is expected).
2. Wait for expectationExpirationManager and check results of expectations

## Expected Output

Expected behavior: previously set results (green) should not be overwritten at expiration.

### PR DESCRIPTION
**Pull request by camrrx**
### Proposed changes

* Prevent inject expectations with existing results from being reprocessed when expiration_time is set.
* Centralize logic to apply both not expired and no result checks

### Testing Instructions

1. Create a simulation with 2 injects: one inject is correctly marked as prevented/detected, while the other is not (because Defender never actually caught it — which is expected).
2. Verify expectations with existing results are not updated

### Related issues

* Closes #4532 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/rest/expectation/ExpectationApi.java [hunk 1]
```diff
@@ -52,7 +52,7 @@ public InjectExpectation deleteInjectExpectationResult(
           "Retrieves inject expectations of agents installed on an asset. If an expiration time is provided, it will return all expectations not expired within this timeframe independently of their results. Otherwise, it will return all expectations without any result.")
```
Comment (guillaumejparis) [inline openaev-api/src/main/java/io/openaev/rest/expectation/ExpectationApi.java:52]: We may need to change this comment ?
