### PR TITLE
[backend] fix(security): fix potential security issue (#1782)

### LINKED ISSUE #1782: [security] Server-Side Request Forgery
## Description

Unsanitized input from the request URL flows into openStream, where it is used as an URL to perform a request. This may result in a Server-Side Request Forgery vulnerability.

Concerned file on 1.8.0 : 
openbas-api/src/main/java/io/openbas/rest/executor/ExecutorApi.java:146

openbas-api/src/main/java/io/openbas/rest/executor/ExecutorApi.java:196

openbas-api/src/main/java/io/openbas/rest/injector/InjectorApi.java:320

### PR DESCRIPTION
**Pull request by gabriel-peze**
### Proposed changes

* Fix potential ssrf issue

### Testing Instructions

1. Run Snyk analisys, it shouldn't report SSRF anymore.
2. Run an OAEV Agent installation, should process as usual
3. Run an Inject on an OAEV Agent, should run as usual

### Related issues

* Closes #1782

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/service/EndpointService.java [hunk 1]
```diff
@@ -807,4 +807,25 @@ public List<FilterUtilsJpa.Option> getOptionsByNameLinkedToFindings(
...
+
+  /**
+   * Construct sanitized JFrog URL from resource path and filename
+   *
+   * @param resourcePath to file
+   * @param filename of the file
+   * @return sanitized URL
+   * @throws MalformedURLException if the url is not well formatted
+   */
+  public URL getJFrogUrl(String resourcePath, String filename) throws MalformedURLException {
```
Comment (savacano28) [inline openaev-api/src/main/java/io/openaev/service/EndpointService.java]: Hi! I also created this PR: https://github.com/OpenAEV-Platform/openaev/pull/4775/changes,
where I extracted these kinds of methods into a utility class.
Maybe you could take a look at this PR first, and then we can merge your code and add some tests.
Ty! :)
