### PR TITLE
[backend] fix(group): sync removing from idp group (#4832)

### LINKED ISSUE #4832: OAEV Trials - ability to to do group mapping for the SSO between Hub & OAEV Trials
## Context
Ability to to do group mapping for the SSO between Hub & OAEV Trials

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* Sync removing from idp group
*

### Testing Instructions

1. Step-by-step how to test
2. Environment or config notes

### Related issues

* Closes #4832
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/service/UserMappingService.java [hunk 1]
```diff
@@ -68,6 +68,18 @@ public void mapCurrentUserWithGroup(String property, User user, List<String> rol
           log.error(String.format("No corresponding group found for group %s", role));
         }
       }
+
+      // If the user has not this group in the groups from the token but he has the group in his
+      // current groups
+      if (groupsFromToken.stream().noneMatch(groupToken -> groupToken.equals(mapping.getIdpGroup()))
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/service/UserMappingService.java:74]: **nitpick**: It can be simplify thanks to only one loop.

Comment (Dimfacion) [reply openaev-api/src/main/java/io/openaev/service/UserMappingService.java:74]: Seen together, no need in the end
