### PR TITLE
[frontend] fix(banner): change start trial button color to white (#5178)

### LINKED ISSUE #5178: [BUG] - Button ' start a trial' does not have the right color
## Description
On the OAEV public demo, button ' start a trial' does not have the right color => should be white

### PR DESCRIPTION
**Pull request by Antoine-Quintin**
### Proposed changes

* Fix "Start a trial" button color in TopBanner component
* Change button background from blue-teal (#007399) to white (#ffffff)
* Change button text color from white to black (#000000) for readability

### Testing Instructions

1- Log in — the trial banner should appear at the top of the page
2 - Verify the "Start a trial" button displays with a white background and dark text

### Related issues

* Closes #5178

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openaev-front/src/public/components/trialbanners/TopBanner.tsx [hunk 1]
```diff
@@ -84,8 +84,8 @@ const TopBanner = ({ bannerText, bannerColor = 'gradient_blue', buttonText, butt
             'fontSize': '0.8rem',
             'textTransform': 'none',
             'lineHeight': 1.2,
-            'background-color': '#007399',
-            'color': 'white',
+            'background-color': '#ffffff',
```
Comment (RomuDeuxfois) [inline openaev-front/src/public/components/trialbanners/TopBanner.tsx]: **todo**: better to use theme instead of hardoding color value
