### PR TITLE
[frontend] fix: improve Alert Accordion UI (#4895)

### LINKED ISSUE #4895: Alert Accordion UI issues: incorrect title hierarchy and spacing
The Alert Accordion UI currently presents several layout and hierarchy issues that impact readability and visual consistency:

The “Scenario Configuration” title has the same font size as the page title, which creates a hierarchy issue and makes the section title appear at the wrong level.

The spacing (padding/margins) around the title is excessive and inconsistent with the rest of the UI

The current title color blends too much with surrounding content, making the section less distinguishable

Steps to reproduce:

Open a page containing the Alert Accordion

Observe the “Scenario Configuration” title and surrounding spacing

Expected behavior:

Section title size should be smaller than the page title

Padding and margins around the title should be reduced and consistent

Title color should clearly separate the accordion section from the rest of the content

Actual behavior:

Section title size matches the page title.

Excessive padding/margins around the title.

Weak visual separation from surrounding content.

Attachments:

Screenshot of the current UI

Image

Two screenshots showing UI adjustments

Image

Image

### PR DESCRIPTION
**Pull request by tibisabau**
### Proposed changes

* Changed "Scenario Configuration" title from `h1` to `h4` variant to establish proper visual hierarchy
* Reduced excessive padding and spacing in AccordionSummary from default 64px to 48px height with custom spacing
* Improved title visual separation by adding warning color and medium font weight

### Testing Instructions

1. Navigate to any scenario page that displays health check warnings (e.g., `/admin/scenarios/{scenarioId}`)
2. Observe the "Scenario Configuration" accordion section
3. Verify the title is visibly smaller than the page title
4. Verify reduced spacing around the accordion title (should be more compact)
5. Verify the title uses warning/orange color for better visual distinction

### Related issues

* Closes #4895

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

The fix addresses all three UI issues reported in #4895 by making targeted changes to the Healthchecks component. The solution uses Material-UI's `sx` prop for custom styling to maintain consistency with the existing codebase patterns. The warning color choice aligns with the accordion's purpose (displaying health check alerts) and provides sufficient contrast without being overly prominent.

**The code in this pull request was generated by GitHub Copilot with the Claude Sonnet 4.5 model.**

### CODE REVIEW

File: openaev-front/src/admin/components/common/healthchecks/Healthchecks.tsx [hunk 1]
```diff
@@ -84,8 +84,24 @@ const Healthchecks = ({ healthchecks, scenarioId }: Props) => {
           margin: 0,
         }}
       >
-        <AccordionSummary expandIcon={<ExpandMore />}>
-          <Typography variant="h1" marginBottom={0}>{t('Scenario configuration')}</Typography>
+        <AccordionSummary
+          expandIcon={<ExpandMore />}
+          sx={{
+            'padding': theme.spacing(1, 2),
+            'minHeight': 48,
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/common/healthchecks/Healthchecks.tsx]: **nitpick**: Please, use theme as much as possible.

File: openaev-front/src/admin/components/common/healthchecks/Healthchecks.tsx [hunk 2]
```diff
@@ -84,8 +84,24 @@ const Healthchecks = ({ healthchecks, scenarioId }: Props) => {
...
+            '&.Mui-expanded': { minHeight: 48 },
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/common/healthchecks/Healthchecks.tsx]: **nitpick**: Please, use theme as much as possible.

File: openaev-front/src/admin/components/common/healthchecks/Healthchecks.tsx [hunk 3]
```diff
@@ -84,8 +84,24 @@ const Healthchecks = ({ healthchecks, scenarioId }: Props) => {
           margin: 0,
         }}
       >
-        <AccordionSummary expandIcon={<ExpandMore />}>
-          <Typography variant="h1" marginBottom={0}>{t('Scenario configuration')}</Typography>
+        <AccordionSummary
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/common/healthchecks/Healthchecks.tsx]: **nitpick**: Please avoid using too much code to fix the UI issue.

This code seems ok
<AccordionSummary expandIcon={<ExpandMore />}>
          <Typography
              variant="h6"
              sx={{
                color: theme.palette.warning.main,
              }}
          >
            {t('Scenario configuration')}
          </Typography>
        </AccordionSummary>

Image

@DeniseMonreale Does it meet your needs ?

Comment (RomuDeuxfois) [reply openaev-front/src/admin/components/common/healthchecks/Healthchecks.tsx]: We should remove spacing to validate this.
