### PR TITLE
[backend] fix(obfuscator): obfuscator options on cmd and psh (#3795)

### LINKED ISSUE #3795: In inject view, it is indicated CMD does not support base64 obfuscation
## Description

In inject view, it is indicated CMD does not support base64 obfuscation:

Image

This should not be displayed (and it is irrelevant here as the payload is using powershell).

We should be able to not propose base64 obfuscation when the payload is using cmd, and propose it when it is compatible.

### PR DESCRIPTION
**Pull request by gabriel-peze**
### Proposed changes

* Remove unecessarry warning message on psh base64 obfuscator option, and remove base64 option on obfuscator when cmd

### Testing Instructions

1. Before running the platform with these changes, start the platform and create a few injects with Command payloads with cmd and psh, warning messages and base64 option should be present.
2. Restart the platform with these changes, new injects shouldn't have the base64 option for cmd, and warning message shouldn't be here for psh.
3. Previously created injects should be fixed too.

### Related issues

* Closes #3795

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/injectors/openaev/util/OpenAEVObfuscationMap.java [hunk 1]
```diff
@@ -21,11 +21,12 @@ public OpenAEVObfuscation(String information, BiFunction<String, String, String>
     }
   }
 
-  public OpenAEVObfuscationMap() {
+  public OpenAEVObfuscationMap(String executor) {
     this.obfuscationMap = new HashMap<>();
     this.registerObfuscation("plain-text", "", this::obfuscatePlainText);
-    this.registerObfuscation(
-        "base64", "CMD does not support base64 obfuscation", this::obfuscateBase64);
+    if (!"cmd".equals(executor)) {
```
Comment (MarineLeM) [inline openaev-api/src/main/java/io/openaev/injectors/openaev/util/OpenAEVObfuscationMap.java]: "cmd" should probably be a constant ?

File: openaev-api/src/main/java/io/openaev/injectors/openaev/util/OpenAEVObfuscationMap.java [hunk 2]
```diff
@@ -21,11 +24,12 @@ public OpenAEVObfuscation(String information, BiFunction<String, String, String>
     }
```
Comment (MarineLeM) [inline openaev-api/src/main/java/io/openaev/injectors/openaev/util/OpenAEVObfuscationMap.java:22]: it seems that "information" is now useless, isn't it ? may be we should remove it ? what do you think?

**Review by MarineLeM — CHANGES_REQUESTED** [review]
Execution no longer works for the existing inject with CMD payload and Base64 obfuscation.

File: openaev-api/src/main/java/io/openaev/injectors/openaev/util/OpenAEVObfuscationMap.java [hunk 3]
```diff
@@ -47,7 +48,7 @@ public String executeObfuscation(String key, String command, String executor) {
   public Map<String, String> getAllObfuscationInfo() {
     Map<String, String> keyInfoMap = new HashMap<>();
     for (Map.Entry<String, OpenAEVObfuscation> entry : obfuscationMap.entrySet()) {
-      keyInfoMap.put(entry.getKey(), entry.getValue().getInformation());
+      keyInfoMap.put(entry.getKey(), "");
```
Comment (MarineLeM) [inline openaev-api/src/main/java/io/openaev/injectors/openaev/util/OpenAEVObfuscationMap.java]: since we remove information on CMD obfuscation, this function getAllObfuscationInfo become completely obsolete

File: openaev-api/src/main/java/io/openaev/rest/payload/service/PayloadService.java [hunk 4]
```diff
@@ -126,8 +126,8 @@ private void updateInjectorContract(Injector injector, Payload payload) {
     injectorContractRepository.save(injectorContractToUpdate);
   }
 
-  private ContractChoiceInformation obfuscatorField() {
-    OpenAEVObfuscationMap obfuscationMap = new OpenAEVObfuscationMap();
+  private ContractChoiceInformation obfuscatorField(String executor) {
+    OpenAEVObfuscationMap obfuscationMap = new OpenAEVObfuscationMap(executor);
     Map<String, String> obfuscationInfo = obfuscationMap.getAllObfuscationInfo();
     return ContractChoiceInformation.choiceInformationField(
         "obfuscator", "Obfuscators", obfuscationInfo, obfuscationMap.getDefaultObfuscator());
```
Comment (MarineLeM) [inline openaev-api/src/main/java/io/openaev/rest/payload/service/PayloadService.java:133]: With no additional details on CMD obfuscation, using ContractChoiceInformation for the obfuscator field is no longer relevant. We should switch it to ContractSelect.

If that’s out of scope for this PR, we can log it as a pain point to address later.

**Review by MarineLeM — APPROVED** [review]

File: openaev-api/src/main/java/io/openaev/rest/payload/service/PayloadService.java (hunk 4 above)
Comment (gabriel-peze) [reply openaev-api/src/main/java/io/openaev/rest/payload/service/PayloadService.java:133]: Tech Pain have been created :)
