### PR TITLE
[backend] fix(perf): deleting an endpoint is taking a lot of time (#4337)

### LINKED ISSUE #4337: Deleting an endpoint is taking a lot of time and sometimes fail, need to refresh
## Description

Deleting an endpoint is taking a lot of time and sometimes fail, need to refresh

## Reproducible Steps

1. Go to the list of endpoint, take one that is used in several scenarios / simulation
2. Try to delete it

=> Nothing happens, needs to wait 30 sec, then reload and the endpoint is gone.

### PR DESCRIPTION
**Pull request by damgouj**
### Proposed changes

* Replace Hibernate query to delete an endpoint to native query to improve perf

### Testing Instructions

1. Get a database with a lot of data on endpoints
2. Delete an endpoint
3. Check the performance and the objects linked to this endpoint

### Related issues

* Closes #4337 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-model/src/main/java/io/openaev/database/repository/EndpointRepository.java [hunk 1]
```diff
@@ -171,6 +171,13 @@ List<Object[]> findAllByNameLinkedToFindingsWithContext(
       nativeQuery = true)
   void setUpdateDate(@Param("updateDate") Instant updateDate, @Param("id") String assetId);
 
+  // Replace Hibernate query by native query for perfs
+  // Native query does the same as Hibernate query here because all "cascade" and other relations
+  // are properly set in the database
+  @Modifying
+  @Query(value = "DELETE FROM assets WHERE asset_id = :assetId", nativeQuery = true)
```
Comment (RomuDeuxfois) [inline openaev-model/src/main/java/io/openaev/database/repository/EndpointRepository.java:178]: Do you have an idea of the time you win with this ?

Comment (damgouj) [reply openaev-model/src/main/java/io/openaev/database/repository/EndpointRepository.java:178]: On my local env with the prerelease database: 10s before, immediately after. But I think it could be interesting to test on prerelease env to really see the difference.

**Comment by savacano28** [comment]
Tested OK
