### PR TITLE
[backend] fix(security): safer use of spel library (#4671)

### LINKED ISSUE #4671: Have a safer use of spel library
## Description

Have a safer use of spel library

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* Improve security
*

### Related issues

* Closes #4671 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/scheduler/jobs/InjectsExecutionJob.java [hunk 1]
```diff
@@ -207,30 +215,71 @@ private void checkErrorMessagesPreExecution(String exerciseId, Inject inject)
...
+                                .getInjectParent()
+                                .getContent()
+                                .get("expectations")
+                                .elements(),
+                            0),
+                        false)
+                    .map(
+                        jsonNode -> {
+                          if (jsonNode
+                              .get("expectation_type")
```
Comment (savacano28) [inline openaev-api/src/main/java/io/openaev/scheduler/jobs/InjectsExecutionJob.java:233]: Question: get("expectation_type") could be null?

Comment (Dimfacion) [reply openaev-api/src/main/java/io/openaev/scheduler/jobs/InjectsExecutionJob.java:233]: I don't think so, if an expectation exists in the array, it has to have a type

**Review by savacano28 — APPROVED** [review]
