### PR TITLE
[backend/frontend] fix: documents for atomic testings (#3956)

### LINKED ISSUE #3956: Error 500 when relaunching Atomic testing / send individual mails with Attachment
## Description

when relaunching an Atomic testing / Send individual mails that has attachment I get "internal error" toast +  "500 error" in the console 

## Environment

OpenBAS version: 1.18.18 - 
Environment => Testing + Prerelease
Chrome  – Version 139.0.7258.157 (Official Build) (arm64)
MacOS sequoia 15.6.1

## Reproducible Steps

1. Launch AN Atomic testing / send individual with some new attachment (or use my tag blvck_test_tag_denise to see my test and relaunch directly) and wait the end of execution

2. A warning window appears, stating that all previous tests will be erased. Confirm the warning

3. Observe the result in the console + display " internal error" as toast

Side Notes:
I think there are another problem with attachement as you cant disable or remove them:

1. Click Update and "Disable attachment" or "Remove from the élément", Confirme Upload and observe the green toast that tell tou that the element has been successfully update ( but is not ;) )

2. Reopen Update and observe how the attachment still attached on the configuration 

 ## Expected Output
- The Atomic Testing should relaunch successfully with the previously inserted attachment

- The Atomic Testing should allow you to disable or remove attachments after uploading

## Actual Output

Relaunch with attachment attempt fails Console displays an Error 500

### PR DESCRIPTION
**Pull request by damgouj**
### Proposed changes

* Fix documents for atomic testings (Back CRUD and Front bugs)

### Testing Instructions

1. Create an atomic testing "mail"
2. Manage documents in it (add, update, remove,...)
3. Execute the atomic test and check if you have documents attached in the mail received
4. Relaunch the atomic testing and check like step 3.

### Related issues

* Closes #3956 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/service/AtomicTestingService.java [hunk 1]
```diff
@@ -119,35 +120,37 @@ public InjectResultOverviewOutput createOrUpdate(AtomicTestingInput input, Strin
...
+                injectDocument.setInject(finalInjectToSave);
+                injectDocument.setDocument(
+                    documentRepository.findById(i.getDocumentId()).orElseThrow());
+              }
+              injectDocument.setAttached(i.isAttached());
+              if (injectId == null) {
+                finalInjectToSave.getDocuments().add(injectDocument);
+              } else {
+                finalInjectToSave.getDocuments().add(injectDocumentRepository.save(injectDocument));
+              }
```
Comment (gabriel-peze) [inline openaev-api/src/main/java/io/openaev/service/AtomicTestingService.java]: nitpick : Maybe use a ternary here.
`finalInjectToSave.getDocuments().add(injectId == null ? injectDocument : injectDocumentRepository.save(injectDocument))`
