### PR TITLE
[frontend] fix(lessons): fix the lessons learned creation (#5537)

### LINKED ISSUE #5537: Unable to Create Lessons Learned
## Description

Creating a Lessons Learned entry is no longer possible.

## Environment

1. OpenAEV version: 2.3.2

## Reproducible Steps

1. Click on Lessons Learned in the left menu
2. The list appears — click on Create

## Expected Output

The user should be able to create a Lessons Learned.

## Actual Output

The following error message is displayed:
An unknown error occurred. Please contact your administrator or the OpenAEV maintainers.

## Screenshots

Image

### PR DESCRIPTION
**Pull request by camrrx**
### Proposed changes

* Extract control from useForm to allow useWatch from textField to receive a valid control instead of undefined 

### Testing Instructions

1. Click on Lessons Learned in the left menu
2. The list appears — click on Create

### Related issues

* Closes #5537

### CODE REVIEW

File: openaev-front/src/admin/components/components/lessons/LessonsTemplateForm.tsx [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import { zodResolver } from '@hookform/resolvers/zod';
 import { Button } from '@mui/material';
+import { useTheme } from '@mui/material/styles';
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/components/lessons/LessonsTemplateForm.tsx:3]: **nitpick**: you could wrap all the fields in a single div with

style={{
  display: 'flex',
  flexDirection: 'column',
  gap: theme.spacing(2),
}}

to avoid repeating the same styling on each field.

Comment (RomuDeuxfois) [reply openaev-front/src/admin/components/components/lessons/LessonsTemplateForm.tsx:3]: **nitpick**: same comment for the other form

**Comment by RomuDeuxfois** [comment]
@camrrx  tests look good. I left a comment about the styling, but it’s not mandatory. Thanks for doing the extra mile and using the theme.

**Review by MarineLeM — APPROVED** [review]

**Comment by EmilieFo17** [comment]
🔍 **PRWatch — Missing Tests Detected**

This PR is linked to a bug issue (#5537) but does not appear to include any test files.

Please consider adding tests to cover the bug fix and prevent regressions.

**Review by RomuDeuxfois — APPROVED** [review]
