### PR TITLE
[frontend] fix(payload): fix export payload in json (#5604)

### LINKED ISSUE #5604: [regression] JSON payload export generates corrupted zip file
## Description
JSON payload export is broken: the exported zip file is corrupted and cannot be opened.

## Environment
- OpenBAS version: 2.3.3

## Reproducible Steps
1. Create a payload
2. Export it as JSON

## Expected Output
A valid, openable zip file.

## Actual Output
A zip file is generated but fails to open with an error.

## Additional Information
- Investigation revealed 3 backend endpoints for JSON payload export — this PR should also include a cleanup of these redundant endpoints.

### PR DESCRIPTION
**Pull request by MarineLeM**
### Proposed changes

* Fix JSON payload export
* On JSON payload import, detection remediations are only created for collectors that exist in the target environment

### Testing Instructions

**Export**
1. Export a payload and verify the zip is valid and openable

**Import**
Context: when importing a payload, detection remediations should only be created for those linked to an existing collector in the target environment.

1. On a first environment, export a payload that has detection remediations for both CrowdStrike and Microsoft Defender
2. Start a fresh OpenAEV instance on a database that only has Microsoft Defender configured
3. Import the previously exported JSON payload
4. Verify:
   - The payload is created successfully
   - The detection remediation linked to Microsoft Defender is created
   - The detection remediation linked to CrowdStrike is **not** created

Close : #5604

### CODE REVIEW

File: openaev-front/src/actions/payloads/payload-actions.ts [hunk 1]
```diff
@@ -65,7 +65,7 @@ export const fetchCollectorsForPayload = (payloadId: string) => (dispatch: Dispa
 
 // -- EXPORT --
 export const exportPayload = (id: string) => {
-  return simplePostCall(`${PAYLOAD_URI}/${id}/export`, {
+  return simpleCall(`${PAYLOAD_URI}/${id}/export`, {
```
Comment (gabriel-peze) [inline openaev-front/src/actions/payloads/payload-actions.ts:68]: @PostMapping(
      path = {PAYLOAD_URI + "/{payloadId}/export", TENANT_PAYLOAD_URI + "/{payloadId}/export"},
      produces = "application/zip")

Into PayloadApi.java it's a POST call, why changing it ?

**Review by gabriel-peze — APPROVED** [review]

File: openaev-front/src/actions/payloads/payload-actions.ts (hunk 1 above)
Comment (MarineLeM) [reply openaev-front/src/actions/payloads/payload-actions.ts:68]: there is two exports endpoints, I will check that

**Review by gabriel-peze — CHANGES_REQUESTED** [review]
Need to modify before merging, approval was a mistake

**Comment by EmilieFo17** [comment]
🤖 **PRWatch — Missing Tests Detected**

This PR fixes a bug (#5604) but does not include any test files covering the change.

Please consider adding tests to prevent regressions.

**Review by gabriel-peze — APPROVED** [review]
Tested OK.
