### PR TITLE
[backend] feat(assetgroups): improve dynamic asset groups (#2895)

### LINKED ISSUE #2895: Evaluate the Safe Number of Agents I Can Run Regularly
## Description

The goal of this issue is to evaluate and determine the optimal number of agents that can be run regularly without compromising the performance and security of the system. This will involve assessing the system's capacity, potential resource constraints, and ensuring that agent operations remain stable and secure even under sustained usage. The objective is to define a safe threshold for agent deployment to maintain efficiency while minimizing risks.

## Environment

1. OS (where OpenBAS server runs): Windows 10 Ubuntu 22.04
2. OpenBAS version: latest
3. OpenBAS client:  CrowdStrike Executor

## Reproducible Steps

The objective of this task is to assess whether it's feasible to run a daily scenario, which contains 50 injects, across 100 agents every day without causing any platform crashes or performance degradation. This will involve testing the system's scalability and evaluating resource usage (CPU, memory, bandwidth, etc.) under the load of running multiple agents simultaneously. The goal is to ensure that the platform can handle the specified workload while maintaining stability and performance.

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* Simpler dynamic asset group logic
*

### Testing Instructions

1. Use dynamic asset group
2. Check everything is still working

### Related issues

* Closes #2895
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/service/AssetGroupService.java [hunk 1]
```diff
@@ -146,28 +143,21 @@ public List<Asset> assetsFromAssetGroup(@NotBlank final String assetGroupId) {
...
-                assets.stream()
-                    .filter(
-                        asset ->
-                            "Endpoint"
-                                .equals(
-                                    asset.getType())) // Filters for dynamic assets are applicable
-                    // only to endpoints
-                    .filter(filters)
+            Specification<Endpoint> specification =
+                computeFilterGroupJpa(assetGroup.getDynamicFilter());
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/service/AssetGroupService.java:154]: **praise**: Looks really good. Do we have any tests on this part ?

File: openaev-api/src/main/java/io/openaev/service/AssetGroupService.java [hunk 2]
```diff
@@ -146,28 +143,21 @@ public List<Asset> assetsFromAssetGroup(@NotBlank final String assetGroupId) {
 
   private List<AssetGroup> computeDynamicAssets(@NotNull final List<AssetGroup> assetGroups) {
     if (assetGroups.stream()
-        .noneMatch(assetGroup -> isEmptyFilterGroup(assetGroup.getDynamicFilter()))) {
+        .allMatch(assetGroup -> isEmptyFilterGroup(assetGroup.getDynamicFilter()))) {
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/service/AssetGroupService.java:146]: **Question**: Does this mean we have a major bug here that nobody noticed? Good to catch it!

File: openaev-api/src/main/java/io/openaev/service/AssetGroupService.java (hunk 1 above)
Comment (Dimfacion) [reply openaev-api/src/main/java/io/openaev/service/AssetGroupService.java:154]: From what I can see on code coverage, we do pass here but there are no specific tests to make sure the logic is working fine. I'll add a few clear tests to make sure it's working as intended

File: openaev-api/src/main/java/io/openaev/service/AssetGroupService.java (hunk 2 above)
Comment (Dimfacion) [reply openaev-api/src/main/java/io/openaev/service/AssetGroupService.java:146]: Looks like it although I don't think it was that common to have several asset groups computed and one of them being totally empty

File: openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java [hunk 3]
```diff
@@ -404,4 +409,221 @@ void optionsByIdTest(Integer numberOfAssetGroupsToProvide, Integer expectedNumbe
...
+
+  @Nested
+  @DisplayName("GET /api/asset-groups - assets resolution")
+  class GetAssetGroupsAssets {
+
+    private Endpoint windowsX86;
+    private Endpoint windowsArm;
+    private Endpoint linuxX86;
+
+    private void createEndpoints() {
```
Comment (RomuDeuxfois) [inline openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java]: **todo**: Why not using fixture and composer ?

File: openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java [hunk 4]
```diff
@@ -404,4 +409,221 @@ void optionsByIdTest(Integer numberOfAssetGroupsToProvide, Integer expectedNumbe
...
+
+      Endpoint linux =
+          EndpointFixture.createEndpointWithPlatform("linux-x86", Endpoint.PLATFORM_TYPE.Linux);
+      linux.setHostname("linux-host-01");
+      linux.setIps(new String[] {"10.0.1.1"});
+      linux.setArch(Endpoint.PLATFORM_ARCH.x86_64);
+      linuxX86 = endpointRepository.save(linux);
+    }
+
+    private AssetGroup saveDynamicGroup(
```
Comment (RomuDeuxfois) [inline openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java]: **todo**: same here

File: openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java [hunk 5]
```diff
@@ -404,4 +409,221 @@ void optionsByIdTest(Integer numberOfAssetGroupsToProvide, Integer expectedNumbe
...
+          JsonPath.read(response, "$[?(@.asset_group_name == '" + groupName + "')]");
+      assertEquals(1, groups.size());
+      return (List<String>) groups.getFirst().get("asset_group_dynamic_assets");
+    }
+
+    @DisplayName(
+        "Given a static asset group with endpoints, should return asset_group_assets with correct IDs")
+    @Test
+    @WithMockUser(isAdmin = true)
+    void given_staticAssetGroupWithEndpoints_should_returnCorrectAssetIds() throws Exception {
```
Comment (RomuDeuxfois) [inline openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java:476]: **question**: I am not sure we need all this tests. This one are the same for me
given_dynamicFilterOnIps_should_returnOnlyMatchingEndpoints
given_dynamicFilterOnHostname_should_returnOnlyMatchingEndpoints
given_dynamicFilterOnArch_should_returnOnlyMatchingEndpoints
given_dynamicFilterOnPlatform_should_returnOnlyMatchingEndpoints

Comment (Dimfacion) [reply openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java:476]: I wanted to make sure all the filters were working fine but I can remove them if you want

Comment (RomuDeuxfois) [reply openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java:476]: Seems overkill to me since we can have a LOT of filters.
Or maybe have on test by filter type ?

Comment (Dimfacion) [reply openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java:476]: It should be simpler now with a parameterized test

File: openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java [hunk 6]
```diff
@@ -404,4 +418,177 @@ void optionsByIdTest(Integer numberOfAssetGroupsToProvide, Integer expectedNumbe
...
+      List<String> expectedIds =
+          expectedEndpointNames.stream().map(name -> endpointsByName.get(name).getId()).toList();
+      assertEquals(expectedIds.size(), dynamicAssetIds.size());
+      assertTrue(dynamicAssetIds.containsAll(expectedIds));
+    }
+
+    static Stream<Arguments> dynamicFilterParameters() {
+      return Stream.of(
+          Arguments.of(
+              "endpoint_platform", "eq", List.of("Windows"), List.of("windowsX86", "windowsArm")),
```
Comment (RomuDeuxfois) [inline openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java]: **todo**: Please use const when you can
Filters.FilterOperator.eq
Endpoint.PLATFORM_TYPE.Windows.name()
ect.

File: openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java (hunk 5 above)
Comment (RomuDeuxfois) [reply openaev-api/src/test/java/io/openaev/rest/asset_group/AssetGroupApiTest.java:476]: That's great !

**Review by RomuDeuxfois — APPROVED** [review]
