### PR TITLE
[frontend/backend] fix: add pagination on list widget (#4410)

### LINKED ISSUE #4410: [SCV] Clickable Domain Dashboard Metrics With Drill-Down Drawer to Inject Results
As a security analyst using the OpenAEV domain dashboard
I want domain-level KPIs (Prevention, Detection, Vulnerability, Human Response, if result are present)  and their success/failure percentages to be fully clickable
So that I can dynamically drill down into the underlying inject results through a drawer view and quickly understand what failed or succeeded

### PR DESCRIPTION
**Pull request by MarineLeM**
### Proposed changes

* Add pagination on list widget
* Add pagination on actionable drawer

### Testing Instructions

Verify if the scenario and simulation dashboard does not have any regression

### Related issues

* Closes #4410 (chunk 2)

### CODE REVIEW

File: openaev-front/src/admin/components/workspaces/custom_dashboards/widgetDataDrawer/WidgetDataDrawer.tsx [hunk 1]
```diff
@@ -32,45 +32,68 @@ const WidgetDataDrawer = () => {
...
       setListConfig(data.list_configuration);
-      setLoading(false);
     }).catch(() => {
       setListConfig(null);
-      setLoading(false);
     });
+  }, [widgetId, filterValues]);
+
+  useEffect(() => {
+    if (!customDashboard || !widgetId || filterValues == null || !seriesIndex) {
```
Comment (GaetanSantucci) [inline openaev-front/src/admin/components/workspaces/custom_dashboards/widgetDataDrawer/WidgetDataDrawer.tsx]: Niptick: !seriesIndex treats 0 as falsy. Using seriesIndex == null avoids that if 0 is valid
