### PR TITLE
[backend/frontend] fix(importexport): payload comming from collector (#4427)

### LINKED ISSUE #4427: Can't export/import a payload comming from a collector
## Description

When I try to import/export a payload comming from atomic red team or filigran database, I get an error

Image

## Environment

1. OS (where OpenAEV server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenAEV version: { e.g. OpenAEV 1.0.2 }
3. OpenAEV client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. export an atomic red team payload
2. import it
3. 

## Expected Output

a custom payload should be imported with the content of the payload

## Actual Output

an error message

### PR DESCRIPTION
**Pull request by EmilieFo17**
### Related issues

* Closes #4427 
*

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/api/payload/PayloadApiExporter.java [hunk 1]
```diff
@@ -35,6 +38,10 @@ public class PayloadApiExporter extends RestBehavior {
   @RBAC(actionPerformed = Action.READ, resourceType = ResourceType.PAYLOAD)
   public ResponseEntity<byte[]> export(@PathVariable @NotBlank final String payloadId)
       throws IOException {
+    Map<String, Boolean> opts = new HashMap<>();
+    opts.put("exclude from payload export", false);
+    IncludeOptions includeOptions = IncludeOptions.of(opts);
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/api/payload/PayloadApiExporter.java:43]: **question**: Include Options is not used here, why ?

Comment (EmilieFo17) [reply openaev-api/src/main/java/io/openaev/api/payload/PayloadApiExporter.java:43]: Because I messed up, I got confused, I made the change, it's better now :)

File: openaev-front/src/components/common/ImportUploader.tsx [hunk 2]
```diff
@@ -23,7 +23,7 @@ const ImportUploader: FunctionComponent<Props> = ({
   color,
   isIconButton = true,
   fileAccepted = '',
-  allowReUpload = false,
+  allowReUpload = true,
```
Comment (RomuDeuxfois) [inline openaev-front/src/components/common/ImportUploader.tsx:26]: **question**: Can you explain why we need this ?

Comment (EmilieFo17) [reply openaev-front/src/components/common/ImportUploader.tsx:26]: Of course, when importing an identical file, there is no reaction from the platform. I discussed this with @guillaumejparis to see whether or not we should generalise on the component.
