### PR TITLE
[backend] Allowing to update a status to ERROR with action COMPLETE Issue/4096

### LINKED ISSUE #4096: [backend] Report implant crash to OpenAEV and update inject status to error
See main issue on the implant: https://github.com/OpenAEV-Platform/implant/issues/78

### PR DESCRIPTION
**Pull request by heditar**
### Proposed changes

* Allowing to update a status to ERROR with action COMPLETE: this will be used by the implant to mark the inject as complete and error when it crashes

### Testing Instructions

* Easier to test with the implant code associated -> put a "panic" in the implant code that should trigger this api call and update the status to error
* You could try to update an implant to Complete/Error with the API 

### Related issues

* Closes #4096
* Implant PR: https://github.com/OpenAEV-Platform/implant/pull/79

### Checklist

- [X] I consider the submitted work as finished
- [X] I tested the code for its functionality
- [X] I wrote test cases for the relevant uses case
- [NA] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality
- [X] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

**Comment by heditar** [comment]
Still testing to validate the case when the impant is detected by the AV

**Comment by heditar** [comment]
> Still testing to validate the case when the impant is detected by the AV

tested

**Comment by heditar** [comment]
Before merging we need to confirm the new behavior in case of failure of the Prerequisites:

before if PR fails -> agent statsu was marked as MAYBE PARTIAL PREVENTED
now  if PR fails -> will be marked as ERROR

File: openbas-api/src/test/java/io/openbas/rest/inject/service/InjectStatusServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+
+import io.openbas.database.model.*;
+import java.util.List;
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.api.extension.ExtendWith;
+import org.mockito.InjectMocks;
+import org.mockito.junit.jupiter.MockitoExtension;
+
+@ExtendWith(MockitoExtension.class)
+public class InjectStatusServiceTest {
```
Comment (damgouj) [inline openbas-api/src/test/java/io/openbas/rest/inject/service/InjectStatusServiceTest.java:13]: Cool thanks :) !
