### PR TITLE
[backend] Create Sent folder if not exists (#296)

### LINKED ISSUE #296: Create the "Sent" IMAP folder if not exists
## Description

When instantiating our cloud environment, the mailbox is created and empty.

Currently, we need to manually connect to the webmail 1 time to avoid this:

```
2023-09-25 15:54:30.042 | openex				2023-09-25 13:54:30.042 ERROR 7 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task |  
-- | -- | --
  |   |   | 2023-09-25 15:54:20.033 | openex |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.18.jar!/:5.3.18] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.18.jar!/:5.3.18] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/java.lang.reflect.Method.invoke(Method.java:577) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at io.openex.injects.email.service.ImapService.connectionListener(ImapService.java:297) ~[classes!/:3.2.2-SNAPSHOT] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at io.openex.injects.email.service.ImapService.syncFolders(ImapService.java:280) ~[classes!/:3.2.2-SNAPSHOT] |  
2x |   |   | 2023-09-25 15:54:20.033 | openex					at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1044) ~[jakarta.mail-1.6.7.jar!/:1.6.7] |  
  |   |   | 2023-09-25 15:54:20.033 | openex					at com.sun.mail.imap.IMAPFolder.checkExists(IMAPFolder.java:431) ~[jakarta.mail-1.6.7.jar!/:1.6.7] |  
  |   |   | 2023-09-25 15:54:20.033 | openex				javax.mail.FolderNotFoundException: Sent not found
```

We need to create the "Sent" email folder on-the-fly if not found.

### PR DESCRIPTION
**Pull request by guillaumejparis**

### CODE REVIEW

File: openex-api/src/main/java/io/openex/injects/email/service/ImapService.java [hunk 1]
```diff
@@ -105,10 +105,20 @@ private void initStore(Environment env) throws Exception {
         int port = env.getProperty("openex.mail.imap.port", Integer.class, 995);
         String username = env.getProperty("openex.mail.imap.username");
         String password = env.getProperty("openex.mail.imap.password");
+        String sentFolder = env.getProperty("openex.mail.imap.sent");
```
Comment (RomuDeuxfois) [inline openex-api/src/main/java/io/openex/injects/email/service/ImapService.java:108]: You should be able to use the property defined in line 64 no ?

    @Value("${openex.mail.imap.sent}")
    private String sentFolder;

Comment (RomuDeuxfois) [reply openex-api/src/main/java/io/openex/injects/email/service/ImapService.java:108]: You can't because you are in the constructor method, my mistake
You can let it like that or use the @PostConstructor annotation to have the injected properties

Lifecycle : constructor call, inject properties, post constructor method call

**Comment by RomuDeuxfois** [comment]
Check if we need to add some flag for folder creation

**Review by RomuDeuxfois — APPROVED** [review]
