### PR TITLE
[backend] fix(security-coverage): return current simulation security platforms (#5109)

### LINKED ISSUE #5109: Security platform score in stix bundle send to OCTI is incorrect
## Description
The STIX bundle sent to OpenCTI does not properly set the score for each security platform on the relationship with the security coverage.

Additionally, the bundle should not include any security platform that has no link to the simulation

Impact : Creates an incoherent state => in OpenCTI the security coverage shows "detected" or "prevented" results, but none of the security platforms have a score.

Image

## Environment

1. OpenAEV version: 2.2.1
2. OpenCTI version : 7.0

## Reproducible Steps

Create a security coverage,  OpenAEV create and run a simulation, "prevented" and "detected" expectation results are collected from Microsoft Defender for sample.
Once all expectations are completed, the simulation finishes and OpenAEV computes a summary as a STIX bundle and sends it to OpenCTI.
Observe the STIX bundle sent to OpenCTI.

Image

## Expected Output

The STIX bundle includes a score on the relationship between each security platform and the security coverage.
Only security platforms that have a link to the simulation are included in the bundle.

## Actual Output

No score is set.
Security platforms with no link to the simulation are still included in the bundle.

### PR DESCRIPTION
**Pull request by gabriel-peze**
### Proposed changes

* Fix Security Coverage bundle generation to return only used security platforms into the bundle, instead of all.

### Testing Instructions

1. Create an automatic Scenario from an OCTI instance
2. Run the Scenario
3. Only the security platform used in the simulation should be returned to OCTI

### Related issues

* Closes #5109

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/ExpectationResultBuilder.java [hunk 1]
```diff
@@ -185,12 +191,19 @@ private static InjectExpectationResult buildForMediaPressure(
...
         .result(result)
         .date(Instant.now().toString())
         .score(score)
         .build();
   }
 
+  private static String getSourceAssetId(Collector collector) {
+    return collector.isExternal() && collector.getSecurityPlatform() != null
+        ? collector.getSecurityPlatform().getId()
+        : collector.getId();
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/ExpectationResultBuilder.java]: Let's not put the collector ID here if it's not related to an actual asset (i.e. security platform)

Leave null if there isn't an asset related to the collector

File: openaev-api/src/main/java/io/openaev/service/stix/SecurityCoverageService.java [hunk 2]
```diff
@@ -565,6 +567,15 @@ private void processCoverageRefs(
...
   }
 
+  private Set<String> getSecurityPlatformAssetIds(List<Inject> injects) {
+    return injects.stream()
+        .flatMap(inject -> inject.getExpectations().stream())
+        .flatMap(expectation -> expectation.getResults().stream())
+        .map(InjectExpectationResult::getSourceAssetId)
+        .filter(Objects::nonNull)
+        .collect(Collectors.toSet());
+  }
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/service/stix/SecurityCoverageService.java]: nitpick: favour encapsulation by not drilling down the attributes but have service methods return the correct information, and each service calls the lower level service if needed
