### PR TITLE
[backend] Add ignore case for findByEmail and add int tests

### LINKED ISSUE #509: Lowercase login email
## Use case

When trying to login with an email with some caps, it fails. We need to lowercase on the API side.

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

* Add ignoreCase in findByEmail
* Add ignoreCase in findAllByEmailIn
* Integration tests for upper, alternating, lower case and unknown user
* Add index for new findByEmailIgnoreCase (lower case))

### Related issues

* issue-509

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openex-api/src/main/java/io/openex/rest/user/form/login/LoginUserInput.java [hunk 1]
```diff
@@ -1,30 +1,24 @@
...
 
+@Builder
+@Getter
+@Setter
+@NoArgsConstructor
+@AllArgsConstructor
 public class LoginUserInput {
 
     @NotBlank(message = MANDATORY_MESSAGE)
+    @JsonProperty("user_login")
```
Comment (RomuDeuxfois) [inline openex-api/src/main/java/io/openex/rest/user/form/login/LoginUserInput.java:17]: Why did you change the property names to json?
I think that break the login page via the front end.

Comment (savacano28) [reply openex-api/src/main/java/io/openex/rest/user/form/login/LoginUserInput.java:17]: Thanks!! I fix it!

**Review by RomuDeuxfois — APPROVED** [review]
