### PR TITLE
[frontend/backend] fix(info): add information related to the xls file and mapper used while imported injects (#1643)

### LINKED ISSUE #1643: Be able to explicitely explain errors from imports
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Import a csv file or json mapper with some missed data
2. And you got : Internal error
image
image

## Expected Output
Message with explicit error

## Actual Output
Internal error

### PR DESCRIPTION
**Pull request by EvaE-Filigran**
Add information related to the xls file and mapper used while imported injects

### Proposed changes

* add field totalRowsAnalysed and calcul, update api-types (backend/frontend)
* add alert part into import dialog (frontend)
* add translations of info (frontend

### Testing Instructions

1. Create mapper Settings -> Data ingestion
2. Create a file xls or download it from the documentation (https://docs.openaev.io/latest/usage/scenario_import/?h=mapper)
3. Create a simulation
4. Use import inject button, select your mapper and xsl file while selecting your mapper you should see how many inject can be created depending on your mapper configuration and error encoured on your xls file.

5. List of potential information:
    "Date set in past",
    "Date set after execution",
    "Expected score undefined",
    "No potential match found",
    "Several matches found",
    "Team not found (contextual team will be created)",
    "Absolute time set without start date"

### Related issues

* Closes #1643

### Checklist

- [X] I consider the submitted work as finished
- [X] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx [hunk 1]
```diff
@@ -273,6 +335,20 @@ const ImportUploaderInjectFromXlsInjects: FunctionComponent<Props> = ({
...
+          <>
+            <Alert severity="info">
+              {((messageInfoMapperXls.at(messageInfoMapperXls.length - 1) ?? '') + t('injects are ready to import'))}
+              <p>{t('ERRORS DETECTED:')}</p>
+              {messageInfoMapperXls.map((msg, i) => (
+                (i != messageInfoMapperXls.length - 1)
+                && <p style={{ whiteSpace: 'pre-line' }} key={i}>{msg}</p>
+              ))}
+            </Alert>
+          </>
```
Comment (gabriel-peze) [inline openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx]: nitpick : Why using <></>, since there is only one element already on them, the <Alert></Alert> element ?

File: openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx [hunk 2]
```diff
@@ -140,6 +197,11 @@ const ImportUploaderInjectFromXlsInjects: FunctionComponent<Props> = ({
         }).length > 0) {
           setNeedLaunchDate(true);
         }
+        const messageInfo: string[] = formatMessages(value.import_message ?? []);
+
+        messageInfo.push(String(value.total_injects ?? 0) + ' / ' + String(value.total_rows_analysed ?? 0) + ' ');
```
Comment (gabriel-peze) [inline openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx]: nitpick : i think it can be more clear like that : 
```
messageInfo.push(`${value.total_injects ?? 0} / ${value.total_rows_analysed ?? 0} `);
```

File: openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx [hunk 3]
```diff
@@ -124,7 +130,58 @@ const ImportUploaderInjectFromXlsInjects: FunctionComponent<Props> = ({
...
+
+    return Object.values(grouped).map(({ code, column, rows }) => {
+      const rowList = rows.join(', ');
+
+      if (column) {
+        return `${t(code)}\n ${t('ON COLUMN')}: ${column}\n ${t('ON ROW')}: ${rowList}`;
+      }
+
+      return `${t(code)}\n ${t('ON ROW')}: ${rowList}`;
+    });
```
Comment (gabriel-peze) [inline openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx]: nitpick : can be reduce to 
```
return Object.values(grouped)
.map(({ code, column, rows }) => `${t(code)}\n ${column ? `${t('ON COLUMN')}: ${column}\n ` : ''}${t('ON ROW')}: ${rows.join(', ')}`);
```

File: openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx (hunk 1 above)
Comment (EvaE-Filigran) [reply openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx]: done

File: openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx (hunk 2 above)
Comment (EvaE-Filigran) [reply openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx]: done

File: openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx (hunk 3 above)
Comment (EvaE-Filigran) [reply openaev-front/src/admin/components/common/injects/ImportUploaderInjectFromXlsInjects.tsx]: done
