### PR TITLE
[frontend] fix(chaining): adding the intermediate scren to choose simulation/scenario type (#5039)

### LINKED ISSUE #5041: [Chaining] Scenario Creation
As a Scenario Builder, 
I want to pick Chaining or Time‑based at creation 
so that the product can tailor all related steps to the correct model.

### PR DESCRIPTION
**Pull request by heditar**
### Proposed changes

* Adding the intermediate screen to select the scenario/simulation type. I created totally new component so we are as more as possible independant from the existing file
* This feature is feature flagged and EE 
* Note:   
  *  scenario creation doesn't support yet sending the boolean as the api is being updated
  * there is some change to the ui compared to the mock so I will also require PO approval
  *
Capture d’écran 2026-03-31 à 09 48 26

Capture d’écran 2026-03-27 à 10 28 47

  

### Testing Instructions

1. Activate the Inject chaining feature flag and start your instance
2. With EE Create a scenario or simulation, you should be able to select a type before the creation form, if you select "Chained" you should see the scenario/exercise_is_chaining parameter added to the post call
3. Without EE you should not bera bale to select chained scenario and if you click on it it should ask you to enter your EE key
4. Deactivaqte the feature you should see the regular form with no change for simulation/scneario creation

### Related issues

* Closes #5041 

### Checklist

is, you are actively helping us to improve the quality of the entire OpenAEV project.
-->

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-front/src/admin/components/common/EngineTypeSelection.tsx [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+    style={{
+      width: 160,
+      height: 60,
+      objectFit: 'contain',
+    }}
+  />
+);
+
+interface EngineTypeSelectionProps {
+  selected: boolean | null;
```
Comment (camrrx) [inline openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: I would use a more explicit type : 
```type EngineType = 'chaining' | 'time-based' | null;```

Comment (heditar) [reply openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: updated

File: openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx [hunk 2]
```diff
@@ -10,18 +10,28 @@ import { SCENARIO_BASE_URL } from '../../../constants/BaseUrls';
...
 
   const dispatch = useAppDispatch();
 
+  const handleTypeSelected = useCallback((chaining: boolean) => {
+    setIsChaining(chaining);
+  }, []);
+
   const onSubmit = (data: ScenarioInput, isScenarioAssistantChecked?: boolean) => {
-    dispatch(addScenario(data)).then(
+    const payload: ScenarioInput = { ...data };
```
Comment (MarineLeM) [inline openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx]: nitpick : this constant is not necessary in this case

File: openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx [hunk 3]
```diff
@@ -10,18 +10,28 @@ import { SCENARIO_BASE_URL } from '../../../constants/BaseUrls';
...
+import { isFeatureEnabled } from '../../../utils/utils';
+import EngineTypeSelection, { type EngineType } from '../common/EngineTypeSelection';
 import ScenarioForm from './ScenarioForm';
+import ScenarioFormChaining from './ScenarioFormChaining';
 
 const ScenarioCreation: FunctionComponent = () => {
   // Standard hooks
+  const isChainingFeatureEnabled = isFeatureEnabled('INJECT_CHAINING');
   const [open, setOpen] = useState(false);
+  const [isChaining, setIsChaining] = useState<EngineType>(isChainingFeatureEnabled ? null : 'time-based');
```
Comment (MarineLeM) [inline openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx]: nitpick : this variable name suppose a boolean but in fact it's a string => it's little bit confusing

File: openaev-front/src/admin/components/common/EngineTypeSelection.tsx [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+                <CardContent sx={{
+                  'display': 'flex',
+                  'flexDirection': 'column',
+                  'alignItems': 'center',
+                  'gap': theme.spacing(1),
+                  'padding': 0,
+                  '&:last-child': { paddingBottom: 0 },
+                }}
+                >
+                  <Box sx={{
```
Comment (MarineLeM) [inline openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: Just a tip: MUI's `<Stack>` component might be a nicer fit here than `<Box display="flex">`
Stack is purpose-built for flex layouts

e.g. `<Stack direction="row" alignItems="center" spacing={1}>`

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx [hunk 5]
```diff
@@ -0,0 +1,358 @@
...
+        onSubmit={handleSubmit((data: ScenarioInput) => onSubmit(data, isScenarioAssistantChecked))}
+      >
+        <Typography
+          variant="h2"
+          gutterBottom
+        >
+          {t('General')}
+        </Typography>
+        <>
+          <TextField
```
Comment (MarineLeM) [inline openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx:99]: Out of scope here since you're just copying an existing component, but for next time — consider using <TextFieldController> instead of <TextField> in forms  — much less code and easier to follow.
e.g.` <TextFieldController variant="standard" name="scenario_name" />`

Same remark applies to almost all field types

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx [hunk 6]
```diff
@@ -0,0 +1,358 @@
...
+            }}
+          >
+            <AccordionSummary expandIcon={<ExpandMore />}>
+              <Typography variant="h2" sx={{ margin: 0 }}>
+                {t('Emails & SMS')}
+              </Typography>
+            </AccordionSummary>
+            <AccordionDetails sx={{
+              display: 'flex',
+              flexDirection: 'column',
```
Comment (camrrx) [inline openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx:237]: There’s no spacing between the form fields in this section. You could add :               
`gap: theme.spacing(2)`

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx [hunk 7]
```diff
@@ -0,0 +1,358 @@
...
+                helperText={errors.scenario_mail_from
+                  ? errors.scenario_mail_from?.message
+                  : (
+                      <span
+                        style={{ color: theme.palette.warning.main }}
+                      >
+                        {t('If you remove the default email address, the email reception for this simulation / scenario will be disabled.')}
+                      </span>
+                    )}
+                inputProps={register('scenario_mail_from')}
```
Comment (camrrx) [inline openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx]: Maybe out of scope, but inputProps is deprecated, you should switch to : 
```
slotProps={{
  htmlInput: register('scenario_mail_from'),
}} 
```

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx [hunk 8]
```diff
@@ -0,0 +1,358 @@
...
+                  checked={isScenarioAssistantChecked}
+                  onChange={() => setIsScenarioAssistantChecked(!isScenarioAssistantChecked)}
+                />
+              )}
+              label={t('Use the scenario assistant')}
+            />
+          )}
+        </>
+        {!isChaining && (
+          <Accordion
```
Comment (camrrx) [inline openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx:221]: You could create new component for the "Emails & Sms" part to reduce the size of this one

File: openaev-front/src/admin/components/common/EngineTypeSelection.tsx [hunk 9]
```diff
@@ -0,0 +1,195 @@
...
+    if (type === 'chaining' && !isEnterpriseEdition) {
+      setEEFeatureDetectedInfo(t('Chaining Scenario'));
+      openEnterpriseEditionDialog();
+      return;
+    }
+    onSelect(type);
+  };
+
+  return (
+    <Box sx={{ marginBottom: theme.spacing(0) }}>
```
Comment (camrrx) [inline openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: It does not seem to add anything here, is it?

File: openaev-front/src/admin/components/common/EngineTypeSelection.tsx [hunk 10]
```diff
@@ -0,0 +1,195 @@
...
+        >
+          <OpenInNew sx={{ fontSize: 14 }} />
+          {t('chaining.doc-link')}
+        </Link>
+      </Box>
+      <Box
+        sx={{
+          display: 'grid',
+          gap: theme.spacing(2),
+          gridTemplateColumns: '1fr 1fr',
```
Comment (camrrx) [inline openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: nitpick : using repeat(2, 1fr) could be a bit more easier to adjust later

File: openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx (hunk 2 above)
Comment (heditar) [reply openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx]: updated in the next commit

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx (hunk 6 above)
Comment (heditar) [reply openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx:237]: updated in the next commit

File: openaev-front/src/admin/components/common/EngineTypeSelection.tsx (hunk 4 above)
Comment (heditar) [reply openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: updated in the next commit

File: openaev-front/src/admin/components/common/EngineTypeSelection.tsx (hunk 10 above)
Comment (heditar) [reply openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: updated in the next commit

File: openaev-front/src/admin/components/common/EngineTypeSelection.tsx (hunk 9 above)
Comment (heditar) [reply openaev-front/src/admin/components/common/EngineTypeSelection.tsx]: updated in the next commit

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx (hunk 5 above)
Comment (heditar) [reply openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx:99]: As discussed offline I won't implement that in this PR

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx (hunk 7 above)
Comment (heditar) [reply openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx]: updated in the next commit

File: openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx (hunk 3 above)
Comment (heditar) [reply openaev-front/src/admin/components/scenarios/ScenarioCreation.tsx]: updated

**Review by MarineLeM — APPROVED** [review]

File: openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx (hunk 8 above)
Comment (heditar) [reply openaev-front/src/admin/components/scenarios/ScenarioFormChaining.tsx:221]: As discussed offline, I won't implement that as part of this PR. There is probably a work to do to merge both from Scenario/simulation so I don't want to take time to create 2 new components

**Review by camrrx — APPROVED** [review]
