### PR TITLE
[backend] fix(teams): fix error while replacing teams in scenario and simulation (#4415)

### LINKED ISSUE #4415: Teams "replaced" can't be added again to a simulation
## Description

Bug occurs when you “replace a team” meaning when you remove a team from the definition’s page with this interface.

When you do this, the action currently keep the team in the database, blocking you from adding it again

Image

## Reproducible Steps

Steps to create the smallest reproducible scenario:

In the tab definition of a simulation
1. Add a team to a simulation and update it
2. Click again on the + "add team" button
3. Remove the team you added with this interface
4. Try to add it again 

## Expected Output

The team is back in the list

## Actual Output

message "internal error"

### PR DESCRIPTION
**Pull request by camrrx**
### Proposed changes

* Fix duplicate key error in exercises_teams_users when replacing exercise teams
* When teams are removed from an exercise, delete the associated (exercise_id, team_id, user_id) entries 

### Testing Instructions

1. Add team in definition tabs in a scenario or simulation
2. Remove it
3. Try to add it again
4. It should be added

### Related issues

* Closes #4415

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openaev-model/src/main/java/io/openaev/database/repository/ScenarioTeamUserRepository.java [hunk 1]
```diff
@@ -29,4 +30,16 @@ public interface ScenarioTeamUserRepository
       nativeQuery = true)
   @Transactional
   void deleteTeamFromAllReferences(@Param("teamIds") List<String> teamIds);
+
+  @Modifying
```
Comment (RomuDeuxfois) [inline openaev-model/src/main/java/io/openaev/database/repository/ScenarioTeamUserRepository.java]: **nitpick**: Should we use @Modifying(clearAutomatically = true, flushAutomatically = true) to clear hibernate cache ?

Comment (camrrx) [reply openaev-model/src/main/java/io/openaev/database/repository/ScenarioTeamUserRepository.java]: Good catch, I added both to ScenarioTeamUserRepository and ExerciseTeamUserRepository
