### PR TITLE
[backend] fix(import): import paylaod with remediation (#5244)

### LINKED ISSUE #5244: Unable to export payloads containing remediation
## Description

Exporting a payload that includes a remediation is not possible. The operation consistently results in an error.

## Environment

1. OAEV 2.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create or select a payload with a remediation
2. Attempt to export the payload

Expected behavior
The payload should be exported successfully, including its remediation.

Actual behavior
An error is generated during the export process, and the payload is not exported.

### PR DESCRIPTION
**Pull request by MarineLeM**
### Proposed changes

* Import payload with remediation

### Related issues

* Closes #5244

### CODE REVIEW

File: openaev-model/src/main/java/io/openaev/database/model/DetectionRemediation.java [hunk 1]
```diff
@@ -45,9 +47,7 @@ public enum AUTHOR_RULE {
 
   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "detection_remediation_payload_id")
-  @JsonSerialize(using = MonoIdSerializer.class)
-  @JsonProperty("detection_remediation_payload_id")
-  @Schema(type = "string")
+  @JsonIgnore
```
Comment (RomuDeuxfois) [inline openaev-model/src/main/java/io/openaev/database/model/DetectionRemediation.java:50]: **nitpick**: good call

File: openaev-model/src/main/java/io/openaev/database/model/Collector.java [hunk 2]
```diff
@@ -34,6 +35,7 @@ public class Collector extends BaseConnectorEntity {
   @NotBlank
   private String name;
 
+  @BusinessId
```
Comment (RomuDeuxfois) [inline openaev-model/src/main/java/io/openaev/database/model/Collector.java:38]: **Question**: With the multi-tenancy feature, collector_type is no longer unique in the database. Can you confirm that it will still work if there are two identical collector_type values with different tenant_ids? We may have overlooked something in this part of the multi-tenancy implementation.

File: openaev-api/src/main/java/io/openaev/api/payload/PayloadApiImporter.java [hunk 3]
```diff
@@ -57,4 +58,23 @@ public ResponseEntity<JsonApiDocument<ResourceObject>> importJson(
       return ResponseEntity.ok().build();
     }
   }
+
+  /**
+   * Removes detection remediations whose collector does not exist in the target database. During
+   * import, the collector is resolved by its business key (type). If not found, the collector field
+   * is null and the remediation must be dropped to avoid constraint violations.
+   */
+  private Payload sanitize(Payload payload) {
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/api/payload/PayloadApiImporter.java:67]: **Todo**: Please add a new test to cover this case.

**Comment by EmilieFo17** [comment]
🤖 **[PRWatch]** — No test files detected in this PR.

This bug-fix PR (linked to #5244) does not appear to include any test coverage for the changes made. Please consider adding tests before merging.

File: openaev-model/src/main/java/io/openaev/database/model/Collector.java (hunk 2 above)
Comment (gabriel-peze) [reply openaev-model/src/main/java/io/openaev/database/model/Collector.java:38]: After an analyse with Damien, once the merge back will be done, the code won't compile anymore.
At this time, we will have to handle some bug fix too, linked to the need of checking id + tenant_id.
And some test again import/export payload (previous model without tenant imported into a tenant environment and export payload from tenant a, and import to tenant b).
How should we handle it ? create right now an issue to handle it at merge back ? or something else ?

Comment (gabriel-peze) [reply openaev-model/src/main/java/io/openaev/database/model/Collector.java:38]: FYI : @damgouj

**Comment by gabriel-peze** [comment]
Hey @RomuDeuxfois 

Every feedback have been tackle, if you have time you can recheck 😊

File: openaev-api/src/main/java/io/openaev/api/payload/PayloadApiImporter.java [hunk 4]
```diff
@@ -47,7 +47,8 @@ public class PayloadApiImporter extends RestBehavior {
   public ResponseEntity<JsonApiDocument<ResourceObject>> importJson(
       @RequestPart("file") @NotNull MultipartFile file) throws Exception {
     try {
-      ZipJsonService.ImportOutput<Payload> response = zipJsonApi.handleImport(file, "payload_name");
+      ZipJsonService.ImportOutput<Payload> response =
+          zipJsonApi.handleImport(file, "payload_name", null, this::sanitize);
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/api/payload/PayloadApiImporter.java:51]: **nitpick**: handleImport(MultipartFile file, String nameAttributeKey) can be removed now

File: openaev-api/src/test/java/io/openaev/api/payload/PayloadApiImporterTest.java [hunk 5]
```diff
@@ -78,6 +84,28 @@ private String performImport(MockMultipartFile zipFile) throws Exception {
         .getContentAsString();
   }
 
+  private ResourceObject buildDetectionRemediationResource(
```
Comment (RomuDeuxfois) [inline openaev-api/src/test/java/io/openaev/api/payload/PayloadApiImporterTest.java]: **nitpick**: Should be put in a fixture class no ?

File: openaev-model/src/main/java/io/openaev/database/model/Collector.java (hunk 2 above)
Comment (RomuDeuxfois) [reply openaev-model/src/main/java/io/openaev/database/model/Collector.java:38]: Yes, you can create an issue direclty, thanks

**Review by RomuDeuxfois — APPROVED** [review]
