### PR TITLE
[backend] Stability improvement

### LINKED ISSUE #4034: [Tooling] - Equip the application with load/performance tests
## Context

OpenBAS lacks load testing, making it hard to validate performance and stability.

## Use case

Run load tests to detect bottlenecks and ensure production readiness.

## Current Workaround

Use external tools manually (Locust, JMeter) without integration.

## Proposed Solution

Provide built-in support or official tooling/docs for load testing OpenBAS.

## Additional Information

Could also be used in CI/CD to catch regressions.

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* Disabling concurrent job for the simulation creation
* Better copy of variable into a newly created simulation as it seems to be taking a lot of CPU usage

### Testing Instructions

1. Test recurring jobs with variable to check if they are created and have all their variables

### Related issues

* Closes #4034
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java [hunk 1]
```diff
@@ -24,6 +25,7 @@
 
 @Component
 @RequiredArgsConstructor
+@DisallowConcurrentExecution
```
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java:28]: Do we need to add this annotation on every job ?

File: openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java [hunk 2]
```diff
@@ -318,21 +318,8 @@ public Exercise toExercise(
...
-                  exerciseVariable.setKey(scenarioVariable.getKey());
-                  exerciseVariable.setValue(scenarioVariable.getValue());
-                  exerciseVariable.setDescription(scenarioVariable.getDescription());
-                  exerciseVariable.setType(scenarioVariable.getType());
-                  exerciseVariable.setExercise(exerciseSaved);
-                  return exerciseVariable;
-                })
-            .toList();
-    this.variableService.createVariables(exerciseVariables);
+    this.variableService.copyVariableFromScenarioForSimulation(
```
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java]: I’d prefer that we keep it as it was for now, to make sure we properly fix the job concurrency issue. We can improve the queries later on. What do you think?

File: openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java (hunk 1 above)
Comment (Dimfacion) [reply openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java:28]: Not on each jobs in my opinion but we should study those that might become a problem if they collide (like they take a longer time than they periodicity). I think it is out of scope for this issue but would you be ok if we add it to our tech pains list ?

Comment (RomuDeuxfois) [reply openbas-api/src/main/java/io/openbas/scheduler/jobs/ScenarioExecutionJob.java:28]: Ok, up to you :)

File: openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java (hunk 2 above)
Comment (Dimfacion) [reply openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java]: I can move it to another PR but honestly, I would rather have that merged asap. It's abnormal that 13% of our CPU time in the last 3 hours has been on this little part of the code ...

Comment (Dimfacion) [reply openbas-api/src/main/java/io/openbas/service/ScenarioToExerciseService.java]: Here's the new PR : https://github.com/OpenAEV-Platform/openaev/pull/4046 :)
