### PR TITLE
[backend/frontend] fix(simulation-reset): status change timeout caused by N+1 queries and in-memory entity deletion on reset (#4336)

### LINKED ISSUE #4336: Reset a simulation takes a lot of time
## Description

For a simulation with 4 injects it takes something like 2 minutes and increasing with injects number.

### PR DESCRIPTION
**Pull request by EvaE-Filigran**
### Proposed changes

The status change logic (changeExerciseStatus) was entirely owned by ExerciseApi, violating separation of concerns. The controller held transactional business logic, direct repository dependencies (EntityManager, PauseRepository, etc.) and a monolithic reset procedure. Additionally, no visual feedback was provided to the user during long-running operations such as a full simulation reset.

Status change was timing out, root cause was in-memory entity loading and
N+1 queries during reset, getting worse as inject count grew.

Backend
-------
- Move changeExerciseStatus from ExerciseApi to ExerciseService
- Replace in-memory deletions with bulk JPQL on reset (pauses, inject statuses, lessons answers) & InjectExpectation handled by Hibernate cascade
- Add @Modifying(clearAutomatically = true) on all bulk deletes
- Schedule MinIO cleanup post-commit to prevent deletion on rollback
- Skip updateScenarios call when validScenarios is empty (reduce store usage)

Frontend
--------
- Add isLoading state with try/finally to guarantee state is always released
- Disable buttons and show <Loader /> during operations

-------
Performance enhancement: reduced execution time from 2 minutes to 9 seconds.
Further frontend optimizations are ongoing: https://github.com/OpenAEV-Platform/openaev/pull/4574

### Testing Instructions

1. Dump the testing db
2. Use Simulation with more that 200 inject and status FINISHED (e.g: bluenoroff)
3. Reset the simulation

### Related issues

* Closes #4336 
*

### Checklist

- [ X] I consider the submitted work as finished
- [X] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [X] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/scheduler/jobs/ScenarioExecutionJob.java [hunk 1]
```diff
@@ -99,7 +99,7 @@ private void cleanOutdatedRecurringScenario() {
           s.setRecurrence(null);
         });
     // Save it
-    this.scenarioService.updateScenarios(scenarios);
+    if (!validScenarios.isEmpty()) this.scenarioService.updateScenarios(validScenarios);
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/scheduler/jobs/ScenarioExecutionJob.java:102]: 👍
