### PR TITLE
[backend/frontend] fix(expectations): add expectations to an inject (#3788)

### LINKED ISSUE #3788: Cannot add type of expectation when creating an inject from a payload
Injects created from a payload with default expectations cannot have expectations of any type added, other than "manual".
And when the payload have default expectations inject cannot have expectations of any type added, other than "manual" and the default from the payload.

### PR DESCRIPTION
**Pull request by damgouj**
### Proposed changes

* Add an API to get the available expectations for an inject

### Testing Instructions

1. Create a human inject (mail/sms/challenge/...) 
2. Checkeyou have by default the expectations filled for this inject
3. Check you can only add/update/remove "manual" expectations
4. Create a technical inject from a payload or from a collector
5. Check you have by default the expectations filled for this payload
6. Check you can add/update/remove the 3 technical expectations (DETECTION/PREVENTION/VULNERABILITY)

### Related issues

* Closes #3788 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [x] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/rest/expectation/ExpectationApi.java [hunk 1]
```diff
@@ -168,4 +169,12 @@ public void updateInjectExpectation(
       @Valid @RequestBody @NotNull InjectExpectationBulkUpdateInput inputs) {
     injectExpectationService.bulkUpdateInjectExpectation(inputs.getInputs());
   }
+
+  @Operation(summary = "Get available expectations for an inject by injector contract id")
+  @GetMapping(INJECTS_EXPECTATIONS_URI + "/available")
+  @RBAC(actionPerformed = Action.READ, resourceType = ResourceType.SIMULATION)
+  public List<Expectation> getAvailableExpectationsForInject(
+      @RequestParam String injectorContractId) {
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/rest/expectation/ExpectationApi.java]: **todo:** injectorContractId can't be null

File: openaev-api/src/main/java/io/openaev/rest/expectation/ExpectationApi.java [hunk 2]
```diff
@@ -168,4 +169,12 @@ public void updateInjectExpectation(
       @Valid @RequestBody @NotNull InjectExpectationBulkUpdateInput inputs) {
     injectExpectationService.bulkUpdateInjectExpectation(inputs.getInputs());
   }
+
+  @Operation(summary = "Get available expectations for an inject by injector contract id")
+  @GetMapping(INJECTS_EXPECTATIONS_URI + "/available")
+  @RBAC(actionPerformed = Action.READ, resourceType = ResourceType.SIMULATION)
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/rest/expectation/ExpectationApi.java]: **question**: I suppose the resourceType sould be ResourceType.INJECT to work on scenario and atomic testing workflow.

File: openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java [hunk 3]
```diff
@@ -796,4 +803,58 @@ private void setupExpectationResults(@NotNull final List<InjectExpectation> inje
...
             injectExpectation -> injectExpectation.setResults(setUpFromCollectors(collectors)));
   }
+
+  /**
+   * Get available expectations for an inject by injector contract id
+   *
+   * @param injectorContractId injector contract id
+   * @return available expectations
+   */
+  public List<io.openaev.model.inject.form.Expectation> getAvailableExpectationsForInject(
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java]: **Nitpick**: As this concerns Expectations (and not Inject Expectations), it could be worth considering moving it to an ExpectationService.
Whatr do you think ?

File: openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java [hunk 4]
```diff
@@ -796,4 +803,58 @@ private void setupExpectationResults(@NotNull final List<InjectExpectation> inje
...
+      String injectorContractId) {
+    InjectorContract injectorContract =
+        injectorContractService.injectorContract(injectorContractId);
+    ObjectNode injectorContractContent = injectorContract.getConvertedContent();
+    boolean isHumanInject = false;
+    List<io.openaev.model.inject.form.Expectation> availableExpectations = new ArrayList<>();
+    Iterator<JsonNode> it = injectorContractContent.get("fields").elements();
+    while (it.hasNext()) {
+      JsonNode node = it.next();
+      if (node.get("key").asText().equals("teams")) {
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java]: **nitpick**: you can use some constant from the InjectorContract file
CONTRACT_ELEMENT_CONTENT_KEY_TEAMS, CONTRACT_ELEMENT_CONTENT_KEY, etc.

File: openaev-api/src/test/java/io/openaev/rest/ExpectationApiTest.java [hunk 5]
```diff
@@ -799,6 +803,103 @@ void bulkUpdateInjectExpectationWithTwoSuccess() throws Exception {
...
+                          + mailInjectorContract.getId())
+                      .accept(MediaType.APPLICATION_JSON))
+              .andExpect(status().is2xxSuccessful())
+              .andReturn()
+              .getResponse()
+              .getContentAsString();
+
+      // -- ASSERT --
+      assertEquals(1, ((List<?>) JsonPath.read(responseMail, "$")).size());
+      assertEquals("MANUAL", JsonPath.read(responseMail, "$.[0].expectation_type"));
```
Comment (RomuDeuxfois) [inline openaev-api/src/test/java/io/openaev/rest/ExpectationApiTest.java]: **todo:** Use EXPECTATION_TYPE enum instead of hardcoding the type.

File: openaev-front/src/actions/expectations/expectation-actions.ts [hunk 6]
```diff
@@ -0,0 +1,10 @@
+import { simpleCall } from '../../utils/Action';
+
+const EXPECTATIONS_URI = '/api/injects/expectations';
+
+const availableExpectationsForInject = (injectorContractId: string = '') => {
```
Comment (RomuDeuxfois) [inline openaev-front/src/actions/expectations/expectation-actions.ts]: **suggestion**: availableExpectationsForInjectorContract could be clearer.

File: openaev-front/src/admin/components/common/injects/expectations/InjectExpectations.tsx [hunk 7]
```diff
@@ -46,12 +45,13 @@ const InjectExpectations: FunctionComponent<InjectExpectationsProps> = ({
...
   const [sortedExpectations, setSortedExpectations] = useState<ExpectationInput[]>([]);
+  const [availableExpectations, setAvailableExpectations] = useState<ExpectationInput[]>([]);
   const [sortBy] = useState('expectation_name');
   const [sortAsc] = useState(true);
 
   // Filter predefinedExpectations already included into expectations
-  const predefinedExpectations = useMemo(() => predefinedExpectationDatas
-    .filter(pe => !sortedExpectations.map(e => e.expectation_type).includes(pe.expectation_type)), [sortedExpectations]);
+  const predefinedExpectations = useMemo(() => availableExpectations
+    .filter(pe => !sortedExpectations.map(e => e.expectation_type).includes(pe.expectation_type) || pe.expectation_type === 'MANUAL'), [sortedExpectations, availableExpectations]);
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/common/injects/expectations/InjectExpectations.tsx:55]: **question**: I am not sure to understand why we have the filter on Manual type.

File: openaev-front/src/admin/components/common/injects/expectations/ExpectationFormCreate.tsx [hunk 8]
```diff
@@ -51,15 +50,14 @@ const ExpectationFormCreate: FunctionComponent<Props> = ({
...
 }) => {
   const { t } = useFormatter();
   const { classes } = useStyles();
 
   const { settings }: { settings: PlatformSettings } = useHelper((helper: LoggedHelper) => ({ settings: helper.getPlatformSettings() }));
-  const [expectationType, setExpectationType] = useState<string>(predefinedExpectations?.length > 0 ? predefinedExpectations[0].expectation_type : 'MANUAL');
+  const [expectationType, setExpectationType] = useState<string>(predefinedExpectations[0].expectation_type);
 
-  const manualExpectationExpirationTime = useExpectationExpirationTime(predefinedExpectations?.length > 0 ? predefinedExpectations[0].expectation_type as InjectExpectation['inject_expectation_type'] : 'MANUAL');
+  const manualExpectationExpirationTime = useExpectationExpirationTime(predefinedExpectations[0].expectation_type as InjectExpectation['inject_expectation_type']);
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/common/injects/expectations/ExpectationFormCreate.tsx]: **nitpick**: This could be renamed now that it simply computes an expirationTime for any type.

File: openaev-front/src/admin/components/common/injects/expectations/InjectExpectations.tsx (hunk 7 above)
Comment (damgouj) [reply openaev-front/src/admin/components/common/injects/expectations/InjectExpectations.tsx:55]: Maybe you have another idea to do this but it's to allow the "multiple" MANUAL expectations as you can have as many expectations as you want.

**Review by RomuDeuxfois — APPROVED** [review]
