### PR TITLE
[backend] fix(duplicate): hibernate exception due to immutable collection (#5011)

### LINKED ISSUE #5011: Duplicating a specific simulation results in error
## Description

When duplicating a simulation, it results in the error : An unknown error occurred. Please contact your administrator or the OpenAEV maintainers.

## Environment
1. SaaS 2.1.8

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open the simulation
2. Click the 3 dots to the right hand side and click duplicate
3. Notice the error

## Actual Output
`TypeError: can't access property "exercise_id", e is undefined
    et Index.tsx:53
    React 14
    D scheduler.production.js:151
react-dom-client.production.js:5892:11
Uncaught (in promise) 
Object { status: 404, id: "eade2b36-bc49-4977-b75e-ccede13876c3", message: "Element not found: Simulation not found" }
​
id: "eade2b36-bc49-4977-b75e-ccede13876c3"
​message: "Element not found: Simulation not found"
​status: 404
​<prototype>: Object { … }
Uncaught (in promise) Error: Permission denied to access property "then"`

## Additional information
I notice that the simulation has 1 validation needed and is currently shown for the status as 'ON-GOING' 

## Screenshots (optional)

Image

### PR DESCRIPTION
**Pull request by RomuDeuxfois**
### Proposed changes

* Fix `UnsupportedOperationException` when duplicating a simulation -> AGAIN 
* Replace immutable collections with mutable collections
* Fix contextual team resolution in duplication. Now correctly points to the copied contextual team instead of the original

### Testing Instructions

1. Create a simulation with teams (including contextual teams), injects, grants and team users
2. Duplicate it via the UI
3. Verify duplication succeeds without error and all data is correctly copied

### Related issues

* Closes #5011

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [x] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/service/ExerciseTeamUserService.java [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+
+@Service
+@RequiredArgsConstructor
+public class ExerciseTeamUserService {
+
+  private final ExerciseTeamUserRepository exerciseTeamUserRepository;
+
+  // -- CRUD --
+
+  public ExerciseTeamUser createExerciseTeamUser(
```
Comment (Dimfacion) [inline openaev-api/src/main/java/io/openaev/service/ExerciseTeamUserService.java:22]: **nitpick :** I'll nitpick again but could you please add comments on public methods of services ?

File: openaev-api/src/test/java/io/openaev/service/GrantServiceTest.java [hunk 2]
```diff
@@ -20,7 +28,7 @@
 @TestExecutionListeners(
     value = {RabbitMQTestListener.class},
     mergeMode = TestExecutionListeners.MergeMode.MERGE_WITH_DEFAULTS)
-public class GrantServiceTest extends IntegrationTest {
+class GrantServiceTest extends IntegrationTest {
```
Comment (Dimfacion) [inline openaev-api/src/test/java/io/openaev/service/GrantServiceTest.java]: **question :** Do we really need to extend IntegrationTest here ? As far as I can tell, we're mocking the calls to the database so maybe we don't need to start the whole Spring Context for this test ?

**Comment by Dimfacion** [comment]
I tested with contextual teams, injects and team users and all seems good. I'm unsure where to find specific grants on a simulation though. Let's discuss it @RomuDeuxfois

File: openaev-api/src/main/java/io/openaev/service/ExerciseTeamUserService.java (hunk 1 above)
Comment (RomuDeuxfois) [reply openaev-api/src/main/java/io/openaev/service/ExerciseTeamUserService.java:22]: Isn’t the method name clear enough?

It feels like overkill to add Javadoc just to say “create Exercise Team User,” doesn’t it?

File: openaev-api/src/test/java/io/openaev/service/GrantServiceTest.java (hunk 2 above)
Comment (RomuDeuxfois) [reply openaev-api/src/test/java/io/openaev/service/GrantServiceTest.java]: Good shot ! I will have a look.

File: openaev-api/src/main/java/io/openaev/service/ExerciseTeamUserService.java (hunk 1 above)
Comment (Dimfacion) [reply openaev-api/src/main/java/io/openaev/service/ExerciseTeamUserService.java:22]: In a way, yes but it also let you know it's straight forward and you don't have to check the source code in case of weird behavior if you know what I mean.
Honestly, it's really a nitpick, I just like to have a description of the method in my IDE when I'm looking for the right service but if you feel it's overkill, I won't mind either

File: openaev-api/src/main/java/io/openaev/service/GrantService.java [hunk 3]
```diff
@@ -66,9 +69,36 @@ public void validateResourceIdForGrant(String resourceId) {
...
+    return new ArrayList<>(
+        sourceGrants.stream()
+            .map(
+                originalGrant ->
+                    createGrant(
+                        originalGrant.getName(),
+                        originalGrant.getGroup(),
+                        targetResourceId,
+                        originalGrant.getGrantResourceType()))
+            .toList());
```
[the remark this answers is not in the document]
Comment (RomuDeuxfois) [reply openaev-api/src/main/java/io/openaev/service/GrantService.java:104]: @copilot open a new pull request to apply changes based on [this feedback](https://github.com/OpenAEV-Platform/openaev/pull/5027#discussion_r2867658224)
