### PR TITLE
[backend/frontend] fix: deduplication security platforms (#2346)

### LINKED ISSUE #2346: Security Platforms should be de-duplicated on the name to avoid mistakes
## Description

Image

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

* Add constraint unicity for asset name ,platform type (for security platform)
* Update ui to includ platform in options/resutls..
image
image
image

### Testing Instructions
Inject/Atomic Testing

1. If you change to branche master and you add more injectExpectation Result from securities platforms with the same name
after running this pr you will be able to see the name of these platform was updated (_n).
*****
1. Add expectationResult for a security platform
2. Add again, check that prevoius security platform is anymore present in the options
3. Delete expectation Result, check you can add again a new result from this sec platform

CRUD Security Platform
1. Create securityPlatform
2. Create new security platfor with the same type and name ->Error
3. Create a new securityplatform
4. Try update last security platform as teh same name of first security platform -> Error

### Related issues

* Closes #2346
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [x] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/InjectExpectationResultUtils.java [hunk 1]
```diff
@@ -17,9 +17,12 @@
 import java.time.Instant;
 import java.util.Collections;
 import java.util.List;
+import java.util.Optional;
 
 public class InjectExpectationResultUtils {
 
+  private static final String NOT_APPLICABLE = null;
```
Comment (damgouj) [inline openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/InjectExpectationResultUtils.java:24]: Interesting way to do it !

File: openaev-api/src/main/java/io/openaev/migration/V4_55__Add_unique_constraint_name_security_platform.java [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+import org.flywaydb.core.api.migration.Context;
+import org.springframework.stereotype.Component;
+
+@Component
+public class V4_55__Add_unique_constraint_name_security_platform extends BaseJavaMigration {
+
+  @Override
+  public void migrate(Context context) throws Exception {
+    try (Statement stmt = context.getConnection().createStatement()) {
+      try {
```
Comment (damgouj) [inline openaev-api/src/main/java/io/openaev/migration/V4_55__Add_unique_constraint_name_security_platform.java]: Did you manage here security platforms for assets and security platforms for collectors ? SourceId comes from several database tables.

Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/migration/V4_55__Add_unique_constraint_name_security_platform.java]: Yes, I did :)

**Comment by savacano28** [comment]
Hi @damgouj, @Dimfacion  I did the changes, ty!

**Review by damgouj — APPROVED** [review]
