### PR TITLE
[backend] fix(connectors): improving connector instance query (#5139)

### LINKED ISSUE #5139: Simulations with a large number of simultaneously executed injects may cause a database lockup
## Description

An inefficient query is blocking progress on inject execution when the database connection pool gets exhausted. These are symptoms observed on a test instance.

We must optimise this bit of code as the incident is likely to appear once a large scenario is designed and executed on any instance.

The problematic code is: https://github.com/OpenAEV-Platform/openaev/blob/69bc9a75d62b8cd095210d06beb1e001e9c26ec6/openaev-api/src/main/java/io/openaev/service/connector_instances/ConnectorInstanceService.java#L109-L130

## Environment

1. OS (where OpenAEV server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenAEV version: { e.g. OpenAEV 1.0.2 }
3. OpenAEV client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. { e.g. Run ... }
2. { e.g. Click ... }
3. { e.g. Error ... }

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

* Refact queries to retrieve the status directly and reduce 2 DB calls -> 1 call.
* Fix topo fom=>from
* Add indexes

### Testing Instructions

Target: Compare latency in this query: hasStartedConnectorInstanceForInjector when you execute an attack.
1. Add 3 injectors using composer
2. Create simulation with at least 50 injects 
3. Execute and check load in database
4. Start and stop connectors to check also the query results

Stopped => False
image
Running => True
image
ConnectorInstant inexistent => True
image

### Related issues

* Closes #5139 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [x] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by GaetanSantucci — DISMISSED** [review]
Test ok

File: openaev-model/src/main/java/io/openaev/database/repository/ConnectorInstanceConfigurationRepository.java [hunk 1]
```diff
@@ -15,7 +16,8 @@ public interface ConnectorInstanceConfigurationRepository
 
   List<ConnectorInstanceConfiguration> findByConnectorInstanceId(String connectorInstanceId);
 
-  interface ConnectorIdsFomDatabase {
+  interface ConnectorIdsFromDatabase {
```
Comment (MarineLeM) [inline openaev-model/src/main/java/io/openaev/database/repository/ConnectorInstanceConfigurationRepository.java:19]: 👍

File: openaev-api/src/main/java/io/openaev/service/connector_instances/ConnectorInstanceService.java [hunk 2]
```diff
@@ -106,26 +105,33 @@ public List<ConnectorInstanceInMemory> getConnectorInstancesInMemoryByConnectorT
     return instancesInMemory;
   }
 
+  /**
+   * Checks whether a started connector instance exists for the given injector.
+   *
+   * <p>Only applies to connectors persisted in the database. If no record is found, meaning the
+   * injector was deployed manually with no attached instance. {@code true} is returned to avoid
```
Comment (MarineLeM) [inline openaev-api/src/main/java/io/openaev/service/connector_instances/ConnectorInstanceService.java]:
```suggestion
   * injector was either deployed manually with no attached instance, or it is an injector that starts automatically and cannot be stopped. {@code true} is returned to avoid
```

File: openaev-api/src/test/java/io/openaev/service/connector_instances/ConnectorInstanceServiceTest.java [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+import org.mockito.InjectMocks;
+import org.mockito.Mock;
+import org.mockito.junit.jupiter.MockitoExtension;
+
+@ExtendWith(MockitoExtension.class)
+class ConnectorInstanceServiceTest {
+
+  @Mock private ConnectorInstanceConfigurationRepository connectorInstanceConfigurationRepository;
+  @Mock private ManagerFactory managerFactory;
+  @Mock private Manager manager;
```
Comment (MarineLeM) [inline openaev-api/src/test/java/io/openaev/service/connector_instances/ConnectorInstanceServiceTest.java]: manager and managerFactory is not used

File: openaev-api/src/test/java/io/openaev/service/connector_instances/ConnectorInstanceServiceTest.java [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+
+      // Act
+      boolean result = connectorInstanceService.hasStartedConnectorInstanceForInjector(injectorId);
+
+      // Assert
+      assertFalse(result);
+    }
+
+    @Test
+    void given_missingStatusInDatabase_should_useFallbackRequestAndReturnTrueWhenRequestSucceeds() {
```
Comment (MarineLeM) [inline openaev-api/src/test/java/io/openaev/service/connector_instances/ConnectorInstanceServiceTest.java:61]: this test and the one below are identical — should we remove one?

**Review by MarineLeM — CHANGES_REQUESTED** [review]

**Comment by MarineLeM** [comment]
test ok

**Review by MarineLeM — APPROVED** [review]
