### PR TITLE
[backend] fix(security): add csrf token management (#1785)

### LINKED ISSUE #1785: [security] Cross-Site Request Forgery (CSRF)
## Description

CSRF protection is disabled by csrf. This allows the attackers to execute requests on a user's behalf.

openbas-api/src/main/java/io/openbas/config/AppSecurityConfig.java:105

### PR DESCRIPTION
**Pull request by gabriel-peze**
### Proposed changes

* Add CSRF token management

### Testing Instructions

1. Verify all platform work as usual

### Related issues

* Closes #1785

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java [hunk 1]
```diff
@@ -72,7 +74,21 @@ public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
...
+                    .ignoringRequestMatchers(
+                        "/api/health",
+                        "/api/comcheck/**",
+                        "/api/player/**",
+                        "/api/settings",
+                        "/api/agent/**",
+                        "/api/implant/**",
+                        "/api/login",
+                        "/api/reset/**",
+                        "/api/**",
```
Comment (damgouj) [inline openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java]: Maybe to think again because you ignore all the url here

File: openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java [hunk 2]
```diff
@@ -72,7 +74,21 @@ public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
...
+                csrf.csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
+                    .csrfTokenRequestHandler(new XorCsrfTokenRequestAttributeHandler())
+                    .ignoringRequestMatchers(
+                        "/api/health",
+                        "/api/comcheck/**",
+                        "/api/player/**",
+                        "/api/settings",
+                        "/api/agent/**",
+                        "/api/implant/**",
+                        "/api/login",
```
Comment (damgouj) [inline openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java]: My logout doesn't work but I don't know if it's normal for master and dev env

**Review by damgouj — CHANGES_REQUESTED** [review]

File: openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java (hunk 2 above)
Comment (gabriel-peze) [reply openaev-api/src/main/java/io/openaev/config/AppSecurityConfig.java]: Maybe you miss the openaev.frontend-url= var in your application-dev.properties.
Setting it allow me to logout and redirect to home page, instead of only logout.

**Review by damgouj — CHANGES_REQUESTED** [review]
it doesn't seem to be working with external API calls

**Comment by gabriel-peze** [comment]
Hey @RomuDeuxfois, @damgouj and @antoinemzs 

I've tagged this PR as "Do not merge" since there is a need for injectors and collectors to be reviewed before merging it.
Antoine send a message to Nicolas to tackle it.

But the code is ready to be reviewed if you want to, until i'll be allowed to merge it.

**Comment by gabriel-peze** [comment]
Need to wait for this [issue](https://github.com/OpenAEV-Platform/client-python/issues/209) to allow this PR to be merged.
Note : Do not forget about the documentation, to add a breaking change with the version.

**Comment by MarineLeM** [comment]
Test ok with this [issue](https://github.com/OpenAEV-Platform/client-python/issues/209)

**Review by MarineLeM — APPROVED** [review]

**Review by damgouj — APPROVED** [review]

**Comment by antoinemzs** [comment]
Good job @gabriel-peze, we should be testing this in integration as soon as possible

**Comment by gabriel-peze** [comment]
Thanks @antoinemzs, i was waiting to create the [doc pr](https://github.com/OpenAEV-Platform/docs/pull/288) before merging :)
I can merge this PR now
