### PR TITLE
[backend] fix: simulation status remains ongoing (#4831)

### LINKED ISSUE #4831: Simulation status remains ongoing even after all expectations are resolved
## Description

There is an issue where a simulation remains in the ongoing status even after all expectations have been successfully resolved.
Image

Here some examples in pre release of simualtion in on going: 

Image

You can check simulation in rpe release: GitLab warns of high-severity 2FA bypass, denial-of-service flaws (248fa028-678a-4f15-90c8-4d16a799cf47)

## Environment

1. OAEV 2.0.14

## Reproducible Steps

1. Start a simulation.
2. Allow the simulation to run until all expectations are resolved.
3. Observe the simulation status.

## Expected Output

Correct Final simulation status

## Actual Output

Ongoing

### PR DESCRIPTION
**Pull request by MarineLeM**
### Proposed Changes

- Fix the initialization of inject expectation results
- **Reminder:** a simulation is considered finished when all inject expectations have a result set

#### Case 1 — Technical inject with vulnerability expectation

1. Create a simulation with a technical inject and add a vulnerability expectation
2. Run the simulation
3. Once the inject finishes, the simulation should remain **"on-going"** until all security platforms return a result
4. Once all security platforms have sent back a result → the simulation should move to **"finished"**

#### Case 2 — Email inject with manual expectations

1. Create a simulation with an email inject, assign a target group of users, and add expectations A and B
2. Run the simulation
3. The simulation should move to **"finished"** only when expectations A and B have a result for **each user** — not before

#### Case 3 — Media pressure inject with manual expectations

1. Create a simulation with a media pressure inject, assign a target group of users, and add expectations A and B
   - Note: media pressure injects have a default expectation of type **article**
2. Run the simulation
3. The simulation should move to **"finished"** only when the article expectation **and** expectations A and B have a result for **each user**

> **Why test all these cases?**
> Email, media pressure, and technical injects do not have the same expectation types.
> Additionally, manual and vulnerability expectations can be added to these cases.

### Related issues

* Closes #4831

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/ExpectationResultBuilder.java [hunk 1]
```diff
@@ -174,31 +174,53 @@ public static void deleteResult(
...
-        .result(Instant.now().toString())
+        .result(result)
         .date(Instant.now().toString())
-        .score(injectExpectation.getExpectedScore())
+        .score(score)
         .build();
   }
 
-  public static InjectExpectationResult buildForVulnerabilityManager() {
+  public static InjectExpectationResult buildForMediaPressure(
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/ExpectationResultBuilder.java:194]: **praise**: Like this way of coding !

File: openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java [hunk 2]
```diff
@@ -812,16 +814,45 @@ public void buildAndSaveInjectExpectations(
...
-    injectExpectations.stream()
-        .filter(ie -> List.of(PREVENTION, DETECTION).contains(ie.getType()))
-        .forEach(
-            injectExpectation -> injectExpectation.setResults(setUpFromCollectors(collectors)));
+
+    injectExpectations.forEach(
+        ie -> {
+          InjectExpectation.EXPECTATION_TYPE type = ie.getType();
+
+          if (List.of(PREVENTION, DETECTION).contains(type) && ie.getAgent() != null) {
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java]: **nitpick**: you can use switch case here

File: openaev-api/src/main/java/io/openaev/scheduler/jobs/InjectsExecutionJob.java [hunk 3]
```diff
@@ -419,9 +419,9 @@ public void execute(JobExecutionContext jobExecutionContext) throws JobExecution
                 }
               });
       // Change status of finished exercises.
+      handleInjectExpectationCollectStatus();
```
Comment (RomuDeuxfois) [inline openaev-api/src/main/java/io/openaev/scheduler/jobs/InjectsExecutionJob.java:422]: **praise** : good catch

File: openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java [hunk 4]
```diff
@@ -812,16 +814,45 @@ public void buildAndSaveInjectExpectations(
...
+            ie.setResults(setUpFromCollectors(collectors));
+
+          } else if (VULNERABILITY.equals(type) && ie.getAgent() != null) {
+            ie.setResults(List.of(buildDefaultForVulnerabilityManagerInFailed()));
+
+          } else if (MANUAL.equals(type) && ie.getUser() != null) {
+            ie.setResults(List.of(buildDefaultForPlayerManualValidation()));
+
+          } else if (ARTICLE.equals(type) && ie.getUser() != null) {
```
Comment (savacano28) [inline openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java]: Maybe we should also add challenge type?

File: openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/ExpectationResultBuilder.java [hunk 5]
```diff
@@ -174,31 +174,53 @@ public static void deleteResult(
...
+      @NotNull final InjectExpectation injectExpectation) {
+    return buildForMediaPressure(Instant.now().toString(), injectExpectation.getExpectedScore());
+  }
+
+  public static InjectExpectationResult buildDefaultForMediaPressure() {
+    return buildForMediaPressure(null, null);
```
Comment (savacano28) [inline openaev-api/src/main/java/io/openaev/utils/inject_expectation_result/ExpectationResultBuilder.java]: Maybe in these null values, could you create some constants like: NO_RESULTS= null, and NO_SCORE=null and reuse them?

File: openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java (hunk 4 above)
Comment (MarineLeM) [reply openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java]: good catch thx, i will add it :)

**Review by savacano28 — APPROVED** [review]
