### PR TITLE
[backend] refactor: refactor processors (#4302)

### LINKED ISSUE #4302: Shodan Injector add asset-creation option
Into Shodan Injector we want to have the ability to select if the contract will create asset (as the logical we have for AWS injector) but within the UI instead of only the docker side

### LINKED ISSUE #5107: Findings fail to be persisted when a duplicate is found in structured output
## Description

If a structured output has any duplicates, findings may fail to be persisted, resulting in no findings related to inject.

## Environment

1. OS (where OpenAEV server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenAEV version: { e.g. OpenAEV 1.0.2 }
3. OpenAEV client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run an nmap TCP connect scan against two endpoints with each a similar port open (e.g. both have 8080 opened)
2. No findings created

## Expected Output

Findings created and consolidated

## Actual Output

Error (see below)

## Additional information

```
2026-03-06T10:59:54.257+01:00 ERROR 585107 --- [OpenAEV API] [pool-6-thread-5] i.o.rest.helper.queue.BatchQueueService  : Error processing batch - Error during ingestion

org.springframework.dao.DataIntegrityViolationException: could not execute batch [Batch entry 31 insert into findings (finding_created_at,finding_field,finding_inject_id,finding_labels,finding_name,finding_type,finding_updated_at,finding_value,finding_id) values (('2026-03-06 09:59:54.248336+00'),('ports'),('8946866d-9b8c-494c-8089-0d1c90102abf'),?,(NULL),('Port'),('2026-03-06 09:59:54.248347+00'),('8080'),('e05e00c9-f865-46b8-94e6-eefc4af1c482')) was aborted: ERROR: duplicate key value violates unique constraint "unique_finding_constraint"
  Détail : Key (finding_inject_id, finding_type, finding_value, finding_field)=(8946866d-9b8c-494c-8089-0d1c90102abf, Port, 8080, ports) already exists.  Call getNextException to see other errors in the batch.] [insert into findings (finding_created_at,finding_field,finding_inject_id,finding_labels,finding_name,finding_type,finding_updated_at,finding_value,finding_id) values (?,?,?,?,?,?,?,?,?)]; SQL [insert into findings (finding_created_at,finding_field,finding_inject_id,finding_labels,finding_name,finding_type,finding_updated_at,finding_value,finding_id) values (?,?,?,?,?,?,?,?,?)]; constraint [unique_finding_constraint]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:290)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:241)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:795)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:758)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:663)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:413)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at io.openaev.rest.inject.service.BatchingInjectStatusService$$SpringCGLIB$$0.handleInjectExecutionCallback(<generated>)
	at io.openaev.rest.helper.queue.executor.BatchExecutionTraceExecutor.handleInjectExecutionCallbackList(BatchExecutionTraceExecutor.java:17)
	at io.openaev.rest.helper.queue.BatchQueueService.lambda$processBufferedBatch$5(BatchQueueService.java:319)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute batch [Batch entry 31 insert into findings (finding_created_at,finding_field,finding_inject_id,finding_labels,finding_name,finding_type,finding_updated_at,finding_value,finding_id) values (('2026-03-06 09:59:54.248336+00'),('ports'),('8946866d-9b8c-494c-8089-0d1c90102abf'),?,(NULL),('Port'),('2026-03-06 09:59:54.248347+00'),('8080'),('e05e00c9-f865-46b8-94e6-eefc4af1c482')) was aborted: ERROR: duplicate key value violates unique constraint "unique_finding_constraint"
  Détail : Key (finding_inject_id, finding_type, finding_value, finding_field)=(8946866d-9b8c-494c-8089-0d1c90102abf, Port, 8080, ports) already exists.  Call getNextException to see other errors in the batch.] [insert into findings (finding_created_at,finding_field,finding_inject_id,finding_labels,finding_name,finding_type,finding_updated_at,finding_value,finding_id) values (?,?,?,?,?,?,?,?,?)]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:97)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:294)
	at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupSingleTable.forEachStatement(PreparedStatementGroupSingleTable.java:67)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.performExecution(BatchImpl.java:264)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.execute(BatchImpl.java:242)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:188)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:663)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:500)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:385)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:41)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1425)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:487)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2324)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:1981)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:439)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:169)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:267)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:562)
	... 17 common frames omitted
Caused by: java.sql.BatchUpdateException: Batch entry 31 insert into findings (finding_created_at,finding_field,finding_inject_id,finding_labels,finding_name,finding_type,finding_updated_at,finding_value,finding_id) values (('2026-03-06 09:59:54.248336+00'),('ports'),('8946866d-9b8c-494c-8089-0d1c90102abf'),?,(NULL),('Port'),('2026-03-06 09:59:54.248347+00'),('8080'),('e05e00c9-f865-46b8-94e6-eefc4af1c482')) was aborted: ERROR: duplicate key value violates unique constraint "unique_finding_constraint"
  Détail : Key (finding_inject_id, finding_type, finding_value, finding_field)=(8946866d-9b8c-494c-8089-0d1c90102abf, Port, 8080, ports) already exists.  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2561)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:672)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:892)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1778)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:279)
	... 35 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "unique_finding_constraint"
  Détail : Key (finding_inject_id, finding_type, finding_value, finding_field)=(8946866d-9b8c-494c-8089-0d1c90102abf, Port, 8080, ports) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2875)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2560)
	... 42 common frames omitted
```

The in-memory collection is as such:
```
0 = {Finding@33976} "Finding(id=null, field=ports, type=Port, value=22, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.125952691Z, updateDate=2026-03-06T10:05:38.125959673Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
1 = {Finding@33977} "Finding(id=null, field=ports, type=Port, value=80, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126091378Z, updateDate=2026-03-06T10:05:38.126094706Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
2 = {Finding@33978} "Finding(id=null, field=ports, type=Port, value=443, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126151705Z, updateDate=2026-03-06T10:05:38.126153254Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
3 = {Finding@33979} "Finding(id=null, field=ports, type=Port, value=5060, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126201678Z, updateDate=2026-03-06T10:05:38.126203218Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
4 = {Finding@33980} "Finding(id=null, field=ports, type=Port, value=8080, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126250485Z, updateDate=2026-03-06T10:05:38.126251870Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
5 = {Finding@33981} "Finding(id=null, field=ports, type=Port, value=1025, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126298547Z, updateDate=2026-03-06T10:05:38.126299934Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
6 = {Finding@33982} "Finding(id=null, field=ports, type=Port, value=1080, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126346187Z, updateDate=2026-03-06T10:05:38.126347418Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
7 = {Finding@33983} "Finding(id=null, field=ports, type=Port, value=5050, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126394051Z, updateDate=2026-03-06T10:05:38.126395413Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
8 = {Finding@33984} "Finding(id=null, field=ports, type=Port, value=5432, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126441833Z, updateDate=2026-03-06T10:05:38.126443255Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
9 = {Finding@33985} "Finding(id=null, field=ports, type=Port, value=8080, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126488943Z, updateDate=2026-03-06T10:05:38.126490359Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
10 = {Finding@33986} "Finding(id=null, field=ports, type=Port, value=8888, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126536983Z, updateDate=2026-03-06T10:05:38.126538268Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
11 = {Finding@33987} "Finding(id=null, field=ports, type=Port, value=9000, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126589130Z, updateDate=2026-03-06T10:05:38.126590539Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
12 = {Finding@33988} "Finding(id=null, field=ports, type=Port, value=9001, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126637681Z, updateDate=2026-03-06T10:05:38.126638938Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
13 = {Finding@33989} "Finding(id=null, field=ports, type=Port, value=9200, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126684992Z, updateDate=2026-03-06T10:05:38.126686292Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
14 = {Finding@33990} "Finding(id=null, field=ports, type=Port, value=10000, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126733146Z, updateDate=2026-03-06T10:05:38.126734531Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
15 = {Finding@33991} "Finding(id=null, field=ports, type=Port, value=10001, labels=[scan], name=null, tags=[], inject=null, creationDate=2026-03-06T10:05:38.126782393Z, updateDate=2026-03-06T10:05:38.126783694Z, assets=[], teams=[], users=[], resourceType=SIMULATION)"
```

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

* Refactor generateFinding functions

### Testing Instructions

You should execute injects capables to generate findings: nuclei, nmap, text, numbr, portscan...

### Related issues

* Closes #4302 
* Closes #5107 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java [hunk 1]
```diff
@@ -92,11 +91,20 @@ public List<String> toFindingUsers(JsonNode jsonNode) {
    * returns empty list.
    */
   public List<String> toFindingTeams(JsonNode jsonNode) {
-    log.warn("Handler {} does not implement toFindingTeams, returning an empty list", type);
+    log.debug("Handler {} does not implement toFindingTeams, returning an empty list", type);
     return Collections.emptyList();
   }
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java]: Could there have been a secondary layer `AbstractFindingOutputProcessor` that exposes these?

AFAICT these methods are called internally so they probably don't need to be part of the public interface.

File: openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java]: This is unused for good reason, since it's an implementation detail

File: openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java (hunk 1 above)
Comment (antoinemzs) [reply openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java]: Also can make protected to not expose accidentally

File: openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+                  .map(ContractOutputContext::from)
+                  .forEach(
+                      contractOutputCtx -> {
+                        OutputProcessor processor =
+                            outputProcessorFactory.getProcessor(contractOutputCtx.type());
+                        JsonNode node = structuredOutput.path(contractOutputCtx.key());
+                        if (!node.isMissingNode()) {
+                          processor.process(executionContext, contractOutputCtx, node);
+                        }
+                      });
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java]: Small duplication here, hence potential for an abstract class here. Not extremely important though, as the code overlap is relatively small and there is a tradeoff in extracting code away from the core logic.

I would consider it though, as a regression could happen if we refactor one of two context processor classes and only test that one.

File: openaev-api/src/test/java/io/openaev/output_processor/CredentialsOutputProcessorTest.java [hunk 3]
```diff
@@ -40,4 +44,28 @@ void shouldReturnFindingValueAsUsernamePassword() throws Exception {
...
+    assertEquals(":pass1", result);
+  }
+
+  @Test
+  @DisplayName("should return empty string when password is empty")
+  void shouldReturnEmptyStringWhenPasswordIsEmpty() throws Exception {
+    JsonNode node = objectMapper.readTree("{\"username\": \"charles\", \"password\": \"\"}");
+    String result = processor.toFindingValue(node);
+    assertEquals("charles:", result);
+  }
```
Comment (antoinemzs) [inline openaev-api/src/test/java/io/openaev/output_processor/CredentialsOutputProcessorTest.java:70]: Are these tests plausible? They seem to contradict the `validate(JsonNode)` implementation.
In any case, please reconsider whether these methods should be part of the public interface.

File: openaev-api/src/test/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandlerTest.java [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+  private Agent agent;
+
+  @BeforeEach
+  void setUp() {
+    this.inject = InjectFixture.getDefaultInject();
+    this.agent = AgentFixture.createDefaultAgentService();
+  }
+
+  @Test
+  @DisplayName("shouldSupportOnlyAgentExecutionContexts")
```
Comment (antoinemzs) [inline openaev-api/src/test/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandlerTest.java]: Please use readable display names

File: openaev-api/src/test/java/io/openaev/rest/inject/service/InjectorExecutionProcessingHandlerTest.java [hunk 5]
```diff
@@ -0,0 +1,143 @@
...
+  @DisplayName("Should support only injector execution contexts")
+  void testSupports() {
+    ExecutionProcessingContext injectorCtx =
+        new ExecutionProcessingContext(inject, null, new InjectExecutionInput(), Map.of());
+
+    assertTrue(handler.supports(injectorCtx));
+  }
+
+  @Test
+  @DisplayName("Should return empty if status is not success or action is not COMPLETE")
```
Comment (antoinemzs) [inline openaev-api/src/test/java/io/openaev/rest/inject/service/InjectorExecutionProcessingHandlerTest.java]: Should it also test that there were no side effects?

File: openaev-api/src/test/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandlerTest.java [hunk 6]
```diff
@@ -0,0 +1,194 @@
...
+
+    Optional<ObjectNode> result = handler.processContext(ctx);
+
+    assertTrue(result.isEmpty());
+    verifyNoInteractions(outputProcessorFactory);
+  }
+
+  @Test
+  @DisplayName("shouldInvokeProcessorOnlyForElementsMarkedAsIsFinding")
+  void shouldInvokeProcessorOnlyForElementsMarkedAsIsFinding() throws Exception {
```
Comment (antoinemzs) [inline openaev-api/src/test/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandlerTest.java]: The mocking does not make it obvious, but this is not what is tested here: you are testing that only when there is a key in the structured output matching the ContractOutputElement's own key that there is a process() call.

File: openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+        .map(
+            structuredOutput -> {
+              // Process findings for each compatible output parser
+              getAllIsFindingCompatibleContractOutputs(outputParsers).stream()
+                  .map(ContractOutputContext::from)
+                  .forEach(
+                      contractOutputCtx -> {
+                        OutputProcessor processor =
+                            outputProcessorFactory.getProcessor(contractOutputCtx.type());
+                        JsonNode node = structuredOutput.path(contractOutputCtx.key());
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java]: There's a risk that if a `ContractOutputType` exists and does not have a corresponding implemented `OutputProcessor`, this might crash and prevent other processors from running.

Please make it so that a missing implementation is logged but does not prevent other processing.

Comment (antoinemzs) [reply openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java]: Apply to other ExecutionProcessingHandlers; consider consolidating (DRYing) this process.

File: openaev-api/src/main/java/io/openaev/rest/inject/service/InjectExecutionService.java [hunk 8]
```diff
@@ -75,54 +68,52 @@ public void handleInjectExecutionCallback(
...
+  public ExecutionProcessingHandler resolveExecutionContext(
+      ExecutionProcessingContext executionContext) {
+    return executionProcessingHandlers.stream()
+        .filter(h -> h.supports(executionContext))
+        .findFirst()
+        .orElseThrow(
+            () ->
+                new IllegalStateException(
+                    "No handler found for execution context: " + executionContext));
+  }
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/rest/inject/service/InjectExecutionService.java]: Do we need this? It looks like the caller passing the arguments should call a specialised method in `InjectExecutionService`, which then passes the correct handler to the main function, e.g.

`BatchingInjectStatusService`: call `InjectExecutionService.processInjectExecutionWithAgent(args)`

`InjectExecutionService.processInjectExecutionWithAgent(args)`: call `InjectExecutionService.processInjectExecution(args, agentExecutionProcessingHandler_instance)`

and conversely with `InjectorExecutionProcessingHandler`.

Here the design looks like we should be able to process the execution context with potentially more than one handler, which we explicitly disallow in implementation.

File: openaev-api/src/main/java/io/openaev/rest/inject/service/InjectStatusService.java [hunk 9]
```diff
@@ -194,7 +194,7 @@ protected void computeExecutionTraceStatusIfNeeded(
   }
 
   public void updateInjectStatus(
-      Agent agent, Inject inject, InjectExecutionInput input, ObjectNode structuredOutput) {
+      Inject inject, Agent agent, InjectExecutionInput input, ObjectNode structuredOutput) {
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/rest/inject/service/InjectStatusService.java:197]: Why this change?

File: openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java [hunk 10]
```diff
@@ -824,4 +824,68 @@ private void setupExpectationResults(@NotNull final List<InjectExpectation> inje
...
+   *
+   * @param inject the inject for which to fetch the expectations
+   * @param agent the agent for which to fetch the expectations
+   * @return the list of inject expectations of type VULNERABILITY for the given inject and agent
+   */
+  private static List<InjectExpectation> fetchVulnerabilityExpectations(
+      Inject inject, Agent agent) {
+    return inject.getExpectations().stream()
+        .filter(exp -> exp.getAgent() != null && exp.getAgent().getId().equals(agent.getId()))
+        .filter(exp -> InjectExpectation.EXPECTATION_TYPE.VULNERABILITY == exp.getType())
```
[the remark this answers is not in the document]
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java:922]: done

File: openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java [hunk 11]
```diff
@@ -824,4 +824,68 @@ private void setupExpectationResults(@NotNull final List<InjectExpectation> inje
...
+    List<InjectExpectation> expectations = fetchVulnerabilityExpectations(inject, agent);
+
+    if (expectations.isEmpty()) {
+      return;
+    }
+
+    InjectExpectationResult result = buildForVulnerabilityManager();
+
+    String label = vulnerable ? VULNERABILITY.failureLabel : VULNERABILITY.successLabel;
+
```
[the remark this answers is not in the document]
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/service/InjectExpectationService.java:904]: done

File: openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java]: Done in the next pr: Asset processor

File: openaev-api/src/test/java/io/openaev/output_processor/CredentialsOutputProcessorTest.java (hunk 3 above)
Comment (savacano28) [reply openaev-api/src/test/java/io/openaev/output_processor/CredentialsOutputProcessorTest.java:70]: Validate check:  jsonNode.hasNonNull(USERNAME) && jsonNode.hasNonNull(PASSWORD), no empty strings, we could add it in other pr.

File: openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java (hunk 1 above)
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/output_processor/AbstractOutputProcessor.java]: Done in the next pr: Asset processors

File: openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java (hunk 2 above)
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java]: Done in the next Pr: Asset processor

File: openaev-api/src/test/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandlerTest.java (hunk 6 above)
Comment (savacano28) [reply openaev-api/src/test/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandlerTest.java]: You are right; I would like to test whether We call the correct process that handles findings using the isFinding flag, but this isn’t really clear in this test. On the other hand, since the flag is no longer used, I’ll delete the test (and also in InjectorExecutionHandlerTest) as its original purpose is obsolete.

File: openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java (hunk 7 above)
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/rest/inject/service/AgentExecutionProcessingHandler.java]: Thank you! I have refactored this part so that it no longer throws an exception. The second part related to refact of this function is addressed in the next PR.

File: openaev-api/src/main/java/io/openaev/rest/inject/service/InjectStatusService.java (hunk 9 above)
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/rest/inject/service/InjectStatusService.java:197]: I just reordered the parameters for better readability and align with the calling methods.

File: openaev-api/src/main/java/io/openaev/rest/inject/service/InjectExecutionService.java (hunk 8 above)
Comment (savacano28) [reply openaev-api/src/main/java/io/openaev/rest/inject/service/InjectExecutionService.java]: The issue here is that processInjectExecution does not know whether the execution is for an agent or an injector, so we determine the correct handler internally using resolveExecutionContext.

Regarding multiple handlers: it might seem like multiple handlers could match, but the agent and injector handlers are mutually exclusive (isAgentExecution() vs isInjectorExecution()), so only one handler can ever be selected per execution context.

I added a comment to indicate that we should have only one handler.

**Comment by savacano28** [comment]
@antoinemzs Hi! I’ve made the requested changes. The PR is ready for review again. Ty! :)

File: openaev-api/src/main/java/io/openaev/rest/inject/service/InjectExecutionService.java (hunk 8 above)
Comment (antoinemzs) [reply openaev-api/src/main/java/io/openaev/rest/inject/service/InjectExecutionService.java]: > Regarding multiple handlers: it might seem like multiple handlers could match, but the agent and injector handlers are mutually exclusive (isAgentExecution() vs isInjectorExecution()), so only one handler can ever be selected per execution context.

I know, however the caller does know. If there is no point in going through several handlers, then both call sites should call a specialised method which passes the correct handler as argument to the generic method.

**Comment by savacano28** [comment]
Hi @antoinemzs! I have made the changes for this issue and #5107, ty!
