### PR TITLE
[backend] fix(performance): delete injects in bulk takes a lot of time (#4479)

### LINKED ISSUE #4479: Delete in bulk takes a lot of time
## Description

When I try delete some injects in bulk in a simualtion or scenario takes a lot of time and something it fails.

## Environment

1. oaev 2.0.0

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create simulation/scenario
2. Add many injects
3. Try delete in bulk some injects

## Expected Output

Taking less time, just like in previous versions

## Actual Output

Image

### PR DESCRIPTION
**Pull request by damgouj**
### Proposed changes

* Update delete inject from hibernate to native for bulk (native query was already done for single inject deletion)

### Testing Instructions

1. Add a lot of injects on a simulation/scenario
2. Delete a lot of them, it must take now less than 2 seconds

### Related issues

* Closes #4479 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openaev-model/src/main/java/io/openaev/database/repository/InjectRepository.java [hunk 1]
```diff
@@ -387,4 +387,8 @@ void deleteAllInjectsWithAttackPatternContractsByScenarioId(
   @Modifying
   @Query(value = "DELETE FROM injects WHERE inject_id = :id", nativeQuery = true)
   void deleteByIdNative(@Param("id") String id);
+
+  @Modifying
+  @Query(value = "DELETE FROM injects WHERE inject_id IN :ids", nativeQuery = true)
+  void deleteByAllIdsNative(@Param("ids") List<String> id);
```
Comment (savacano28) [inline openaev-model/src/main/java/io/openaev/database/repository/InjectRepository.java]: ids

File: openaev-api/src/main/java/io/openaev/rest/inject/service/InjectService.java [hunk 2]
```diff
@@ -411,7 +411,6 @@ public InjectResultOverviewOutput relaunch(String id) {
 
   @Transactional
   public void delete(String id) {
-    injectDocumentRepository.deleteDocumentsFromInject(id);
     injectRepository.deleteById(id);
```
Comment (savacano28) [inline openaev-api/src/main/java/io/openaev/rest/inject/service/InjectService.java:414]: Maybe you could check if this function is no longer used in the repository?

File: openaev-api/src/main/java/io/openaev/rest/inject/InjectApi.java [hunk 3]
```diff
@@ -433,11 +433,8 @@ public List<Inject> bulkDelete(@RequestBody @Valid final InjectBulkProcessingInp
     List<Inject> injectsToDelete =
         getInjectsAndCheckInputForBulkProcessing(input, Grant.GRANT_TYPE.PLANNER);
 
-    // FIXME: This is a workaround to prevent the GUI from blocking when deleting elements
-    injectsToDelete.forEach(inject -> inject.setListened(false));
-
     // Bulk delete
-    this.injectService.deleteAll(injectsToDelete);
+    this.injectService.deleteAllByIds(injectsToDelete.stream().map(Inject::getId).toList());
     return injectsToDelete;
```
Comment (savacano28) [inline openaev-api/src/main/java/io/openaev/rest/inject/InjectApi.java:438]: Maybe you could check if we can avoid return the injectsToDelete?

**Comment by savacano28** [comment]
Tests: OK
br : image
master: 
image

File: openaev-api/src/main/java/io/openaev/rest/inject/InjectApi.java (hunk 3 above)
Comment (damgouj) [reply openaev-api/src/main/java/io/openaev/rest/inject/InjectApi.java:438]: Yes the Front uses the return ;)
