### PR TITLE
[backend] chore: fix serialization of user session (#4889)

### LINKED ISSUE #4889: Fix serialization of the user session
When the backend restarts, user sessions are lost because they aren't properly serialized.

### PR DESCRIPTION
**Pull request by guillaumejparis**
### Proposed changes

* Properly serialize user session
* Fix warning log from logback
* Add a started message in dev when baclend ready

### Testing Instructions

1. Step-by-step how to test
2. Environment or config notes

### Related issues

* Closes #4889
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openaev-model/src/main/java/io/openaev/database/model/User.java [hunk 1]
```diff
@@ -35,7 +36,7 @@
       name = "Player.tags-organization",
       attributeNodes = {@NamedAttributeNode("tags"), @NamedAttributeNode("organization")})
 })
-public class User implements Base {
+public class User implements Base, Serializable {
```
Comment (antoinemzs) [inline openaev-model/src/main/java/io/openaev/database/model/User.java]: to remove

Comment (guillaumejparis) [reply openaev-model/src/main/java/io/openaev/database/model/User.java]: done

File: openaev-api/src/main/java/io/openaev/tools/AppReadyListener.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+public class AppReadyListener {
+
+  @EventListener(ApplicationReadyEvent.class)
+  public void onApplicationReady(ApplicationReadyEvent event) {
+    Duration timeTaken = event.getTimeTaken();
+
+    long minutes = timeTaken.toMinutes();
+    long seconds = timeTaken.toSecondsPart();
+    System.out.println("✅ Application is ready!");
+    System.out.printf("⏱️ Startup time: %d min %d sec%n", minutes, seconds);
```
Comment (antoinemzs) [inline openaev-api/src/main/java/io/openaev/tools/AppReadyListener.java]: Please use slf4j for logging, INFO level should be fine

Comment (guillaumejparis) [reply openaev-api/src/main/java/io/openaev/tools/AppReadyListener.java]: image

File: openaev-api/src/main/resources/logback-spring.xml [hunk 3]
```diff
@@ -11,6 +11,11 @@
             <appender-ref ref="STDOUT" />
         </root>
     </springProfile>
+    <springProfile name="dev">
+      <logger name="io.openaev.tools.AppReadyListener" level="INFO" additivity="false">
+        <appender-ref ref="STDOUT"/>
+      </logger>
+    </springProfile>
```
Comment (guillaumejparis) [inline openaev-api/src/main/resources/logback-spring.xml]: I did a custom logger for my class **only in dev** to display application startup message even if dev is in log level error 
@antoinemzs wdyt ?

Comment (guillaumejparis) [reply openaev-api/src/main/resources/logback-spring.xml]: Deleted

File: openaev-api/src/main/java/io/openaev/tools/AppReadyListener.java (hunk 2 above)
Comment (guillaumejparis) [reply openaev-api/src/main/java/io/openaev/tools/AppReadyListener.java]: Deleted
