### PR TITLE
[frontend] Issue on PDF export

### LINKED ISSUE #3443: PDF export of report is not working
## Description
When I try to export my report in PDF, I get an error message

Image

## How to reproduce
- go to https://prerelease.obas.staging.filigran.io/reports/a9cbe8e1-d760-4603-9d8c-9b9075fd5615/exercise/b99a0b53-b5cc-4fbc-8564-7eaef1e6a06b

- click on PDF export

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* If no expectations, still display an empty div for the report to be displayed 
*

### Testing Instructions

1. Create a report without any expectations
2. Try to generate a PDF

### Related issues

* Closes #3443
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

Be careful since we modified AtomicTestingResult that there are no side effect (I didn't see any but be careful)

### CODE REVIEW

File: openbas-front/src/admin/components/simulations/simulation/reports/SimulationReportPage.tsx [hunk 1]
```diff
@@ -158,7 +158,19 @@ const SimulationReportPage: FunctionComponent = () => {
...
+                  <ResponsePie
+                    expectationResultsByTypes={reportData.exerciseExpectationResults}
+                    disableChartAnimation
+                  />
+                ) : (
+                  <div
+                    id="score_details"
+                    style={{ height: 1 }}
+                  >
+                    <p>&nbsp;</p>
```
Comment (impolitepanda) [inline openbas-front/src/admin/components/simulations/simulation/reports/SimulationReportPage.tsx:171]: Should we display a message saying that there are no expectation results yet, maybe ?

**Review by impolitepanda — APPROVED** [review]

File: openbas-front/src/admin/components/simulations/simulation/reports/SimulationReportPage.tsx (hunk 1 above)
Comment (Dimfacion) [reply openbas-front/src/admin/components/simulations/simulation/reports/SimulationReportPage.tsx:171]: I asked Product team and they told me that since this part can be hidden when you create the report, we should let the customer handle this.
