### PR TITLE
[frontend] fix(scv): display on domain widget (#4292)

### LINKED ISSUE #4292: [SCV]  Display and interact with Security Domains metrics on the dashboard
As a CISO
I want view and interact with Security Domain metrics on the dashboard
So that I can quickly understand the security posture across different domains and take action where necessary

### PR DESCRIPTION
**Pull request by gabriel-peze**
### Proposed changes

* Review the display of the domain widget, to align with colors and rules defined by product

### Testing Instructions

1. Load a security coverage widget on a dashboard, it should display the colors as defined by the product

### Related issues

* Closes #4292

### CODE REVIEW

File: openaev-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/domains/SecurityDomainsWidgetUtils.tsx [hunk 1]
```diff
@@ -69,3 +120,155 @@ export function buildOrderedDomains(items: IconBarElement[]): IconBarElement[] {
...
+ */
+export const determinePercentage = (esAvgs: EsAvgs): EsAvgsExtended => {
+  const mappedAverage: EsAvgsExtended = {
+    ...esAvgs,
+    security_domain_average: [],
+  };
+
+  // Manage Security Domain Average, represent the list of available average to display on the widget
+  esAvgs.security_domain_average
+    .filter(domainAvgs => domainAvgs.label !== 'To classify')
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/domains/SecurityDomainsWidgetUtils.tsx:268]: Could be great to have a constante for this domain

File: openaev-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/domains/SecurityDomainsWidgetUtils.tsx [hunk 2]
```diff
@@ -2,8 +2,59 @@ import { Groups, HelpOutlined, ImportantDevices, Language, Lock, Mail, WebAsset
...
+    data: [],
+  },
+];
+
+const SUCCESS_COLOR = 'rgb(2,129,8)';
+const INTERMEDIATE_COLOR = 'rgb(255 216 0)';
+const WARNING_COLOR = 'rgb(245, 166, 35)';
+const FAILED_COLOR = 'rgb(220, 81, 72)';
+const PENDING = 'rgba(248,243,243,0.37)';
+const UNKNOWN = 'rgba(73,72,72,0.37)';
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/domains/SecurityDomainsWidgetUtils.tsx:56]: We already use several colors across the application. It would be great to consolidate them and move them into the theme file.

File: openaev-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/domains/SecurityDomainsWidgetUtils.tsx [hunk 3]
```diff
@@ -69,3 +120,155 @@ export function buildOrderedDomains(items: IconBarElement[]): IconBarElement[] {
...
+    case data.find(expectationExtended => expectationExtended?.status === STATUS_WARNING) != null:
+      return WARNING_COLOR;
+    case data.find(expectationExtended => expectationExtended?.status === STATUS_INTERMEDIATE) != null:
+      return INTERMEDIATE_COLOR;
+    case data.find(expectationExtended => expectationExtended?.status === STATUS_SUCCESS) != null:
+      return SUCCESS_COLOR;
+    default:
+      return EMPTY_DATA;
+  }
+};
```
Comment (RomuDeuxfois) [inline openaev-front/src/admin/components/workspaces/custom_dashboards/widgets/viz/domains/SecurityDomainsWidgetUtils.tsx:141]:
```suggestion
const colorByAverageForDomain = (data: EsExpectationExtended[]): string => {
  switch (true) {
    case data.some(expectationExtended => expectationExtended?.status === STATUS_FAILURE):
      return FAILED_COLOR;
    case data.some(expectationExtended => expectationExtended?.status === STATUS_WARNING):
      return WARNING_COLOR;
    case data.some(expectationExtended => expectationExtended?.status === STATUS_INTERMEDIATE):
      return INTERMEDIATE_COLOR;
    case data.some(expectationExtended => expectationExtended?.status === STATUS_SUCCESS):
      return SUCCESS_COLOR;
    default:
      return EMPTY_DATA;
  }
};
```

Seems to be simplier
